@startuml DiagramaContextoMiembro
left to right direction
skinparam linetype polyline

state "SESION_CERRADA" as NoAuth
state "SISTEMA_DISPONIBLE" as Menu

state "TAREAS_ABIERTO" as ListProgramas

state "INVITACIONES_ABIERTO" as ListInvitaciones
state "INVITACION_ABIERTO" as EditInvitacion

[*] --> NoAuth

NoAuth --> Menu : iniciarSesion()

Menu --> NoAuth : cerrarSesion()
Menu --> ListProgramas: abrirTareas()
Menu --> ListInvitaciones: abrirInvitaciones()

ListProgramas --> ListProgramas: marcarCompletada()
ListProgramas --> Menu: completarGestion()

ListInvitaciones --> EditInvitacion: editarInvitacion()
ListInvitaciones --> Menu: completarGestion()
ListInvitaciones --> ListInvitaciones: abrirInvitaciones()


EditInvitacion --> ListInvitaciones: abrirInvitaciones()
EditInvitacion --> EditInvitacion: editarInvitacion()
@enduml