@startuml validarConflicto-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":Estado origen SdR" as EstadoOrigen
rectangle #CDEBA5 ":Estado destino SdR" as EstadoDestino

package "validarConflicto()" {
    rectangle #629EF9 ValidarConflictoView
    rectangle #b5bd68 ValidarConflictoController
    rectangle #F2AC4E RepositorioDominio
    rectangle #F2AC4E EntidadDominio
}

EstadoOrigen --> ValidarConflictoView: validarConflicto()
ValidarConflictoView --> ValidarConflictoController: coordinarCasoUso()
ValidarConflictoController --> RepositorioDominio: consultarOModificarDominio()
RepositorioDominio -- EntidadDominio
ValidarConflictoView --> EstadoDestino: presentaResultado()

@enduml
