@startuml consultarUsuario-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":Usuarios Abierto" as UsuariosAbierto

package consultarUsuario as "consultarUsuario()" {
    rectangle #629EF9 ConsultarUsuarioView
    rectangle #b5bd68 UsuarioController
    rectangle #F2AC4E UsuarioRepository
    rectangle #F2AC4E Usuario
}

UsuariosAbierto -r-> ConsultarUsuarioView: consultarUsuario()
ConsultarUsuarioView -d-> UsuarioController: consultarUsuario(usuarioId)
UsuarioController --> UsuarioRepository: findById(usuarioId)
UsuarioRepository -- Usuario
@enduml