@startuml exportarAlumnos-analisis
skinparam linetype polyline

note "<<abstracto>>\nInvocado desde CU-04: exportarConfiguracionGlobal" as N1
package exportarAlumnos as "exportarAlumnos()" {
    rectangle #629EF9 VistaExportacionAlumnos
    rectangle #b5bd68 ControladorExportacion
    rectangle #F2AC4E Alumno
}

VistaExportacionAlumnos -d-> ControladorExportacion: prepararDatos()
ControladorExportacion --> Alumno: obtenerTodos()
ControladorExportacion --> VistaExportacionAlumnos: ficheroJSON

@enduml
