@startuml abrirConvocatorias-analisis
skinparam backgroundColor white
skinparam shadowing false
skinparam DefaultFontColor black
skinparam DefaultFontSize 12
skinparam linetype polyline

rectangle #CDEBA5 "Navegación Sistema" as NavegacionSistema
rectangle #CDEBA5 "CONVOCATORIAS_ABIERTAS" as ConvocatoriasAbiertas

package "abrirConvocatorias()" as abrirConvocatorias {
    rectangle "ListarConvocatoriasView" as ListarConvocatoriasView #629EF9
    rectangle "ConvocatoriaController" as ConvocatoriaController #b5bd68
    rectangle "ConvocatoriaRepository" as ConvocatoriaRepository #F2AC4E
    rectangle "Convocatoria" as Convocatoria #F2AC4E
}

rectangle #CDEBA5 ":Collaboration AbrirConvocatoria" as AbrirConvocatoria
rectangle #CDEBA5 ":Collaboration AbrirPanelPrincipal" as AbrirPanelPrincipal

NavegacionSistema -r-> ListarConvocatoriasView: abrirConvocatorias()

ListarConvocatoriasView -d-> ConvocatoriaController: listarConvocatorias() : List<Convocatoria>
ConvocatoriaController -d-> ConvocatoriaRepository: obtenerTodas() : List<Convocatoria>
ConvocatoriaRepository -- Convocatoria

ListarConvocatoriasView ..> AbrirConvocatoria: abrirConvocatoria(convocatoriaId)
ListarConvocatoriasView ..> AbrirPanelPrincipal: abrirPanelPrincipal()

ListarConvocatoriasView ..> ConvocatoriasAbiertas: <<finalizar>>

@enduml
