@startuml editarRecompensa

skinparam linetype polyline

state in1 as "RECOMPENSA_ABIERTA"
in1 -[#green]-> editarRecompensa
note on link
editarRecompensa()
end note

state editarRecompensa as "editarRecompensa()" {

    state " " as EditandoDatos
    state " " as CambiosGuardados

    [*] -[#green]-> EditandoDatos
    note on link
    <b>Coordinador</b> solicita editar recompensa
    end note

    EditandoDatos -[#green]-> CambiosGuardados
    note on link
    <b>Sistema</b> presenta datos editables de la recompensa
    <b>Sistema</b> permite introducir modificaciones
    <b>Coordinador</b> introduce cambios y solicita guardar
    <b>Sistema</b> registra los cambios
    end note

    EditandoDatos -[#red]-> [*]
    note on link
    <b>Coordinador</b> solicita cancelar edición
    end note

    CambiosGuardados -[#green]-> [*]
    note on link
    <b>Sistema</b> presenta confirmación de cambios guardados
    end note
}


editarRecompensa -[#green]-> RECOMPENSA_ABIERTA
note on link
Recompensa editada
end note

editarRecompensa -[#red]-> RECOMPENSA_ABIERTA
note on link
Edición cancelada
end note

editarRecompensa -[#green]-> RECOMPENSAS_ABIERTAS
note on link
eliminarRecompensa()
end note

editarRecompensa -[#green]-> RECOMPENSAS_ABIERTAS
note on link
abrirRecompensas()
end note


@enduml
