@startuml crearAsignatura-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":Asignaturas Abierto" as AsignaturasAbierto
rectangle #CDEBA5 ":Collaboration EditarAsignatura" as EditarAsignatura

package crearAsignatura as "crearAsignatura()" {
    rectangle #629EF9 CrearAsignaturaView
    rectangle #b5bd68 AsignaturaController
    rectangle #F2AC4E AsignaturaRepository
    rectangle #F2AC4E Asignatura
}

AsignaturasAbierto --> CrearAsignaturaView: crearAsignatura()


CrearAsignaturaView -d-> AsignaturaController: validarDatosMínimos(título, código, cursoAcadémico) : boolean

AsignaturaController --> AsignaturaRepository: verificarUnicidad(código) : boolean

CrearAsignaturaView --> AsignaturaController: crearAsignatura(título, código, cursoAcadémico) : Asignatura

AsignaturaController --> AsignaturaRepository: crear(título, código, cursoAcadémico) : Asignatura

AsignaturaRepository -- Asignatura

CrearAsignaturaView ..> EditarAsignatura: <<include>> editarAsignatura(asignaturaNueva)

@enduml
