@startuml abrirAlumnos-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":Sistema Disponible" as SistemaDisponible

package abrirAlumnos as "abrirAlumnos()" {
    rectangle #629EF9 AbrirAlumnosView
    rectangle #b5bd68 AlumnoController
    rectangle #F2AC4E AlumnoRepository
    rectangle #F2AC4E Alumno
}

SistemaDisponible -r-> AbrirAlumnosView: abrirAlumnos()
AbrirAlumnosView -d-> AlumnoController: listarAlumnos(filtros)
AlumnoController --> AlumnoRepository: findAll(filtros)
AlumnoRepository -- Alumno
@enduml