@startuml abrirGrados-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":Sistema Disponible" as SistemaDisponible

package abrirGrados as "abrirGrados()" {
    rectangle #629EF9 ListarGradosView
    rectangle #b5bd68 GradoController
    rectangle #F2AC4E GradoRepository
    rectangle #F2AC4E Grado
}

rectangle #CDEBA5 ":Sistema Disponible" as SistemaDisponibleSalida
rectangle #CDEBA5 ":Collaboration CrearGrado" as CrearGrado
rectangle #CDEBA5 ":Collaboration EditarGrado" as EditarGrado
rectangle #CDEBA5 ":Collaboration EliminarGrado" as EliminarGrado
rectangle #CDEBA5 ":Collaboration ImportarGrados" as ImportarGrados

SistemaDisponible -r-> ListarGradosView: abrirGrados()

ListarGradosView -d-> GradoController: listarGrados() : List<Grado>

GradoController --> GradoRepository: obtenerTodos() : List<Grado>

GradoRepository -- Grado

ListarGradosView --> GradoController: filtrarGrados(criterio) : List<Grado>

GradoController --> GradoRepository: buscarPorCriterio(criterio) : List<Grado>

ListarGradosView ..> SistemaDisponibleSalida: completarGestion()
ListarGradosView ..> CrearGrado: crearGrado()
ListarGradosView ..> EditarGrado: editarGrado()
ListarGradosView ..> EliminarGrado: eliminarGrado()
ListarGradosView ..> ImportarGrados: importarGrados()

@enduml
