@startuml

skinparam nodesep 60
skinparam ranksep 60
skinparam linetype polyline
skinparam NoteBackgroundColor lightyellow
skinparam NoteBorderColor gray
skinparam StateBackgroundColor #F5F5F5
skinparam StateBorderColor gray

state "editarSolicitudDispensa()" as editarSolicitud {

    state " " as Paso1

    [*] -[#green]-> Paso1 
    note on link
      <b>Director de Grado</b> solicita editar la dispensa
      <b>Sistema</b> habilita el formulario con los datos actuales
    end note    
    
    Paso1 -[#green]-> [*]
    note on link
      <b>Director de Grado</b> modifica campos permitidos:
      • Estado de la Dispensa y Observaciones/Resolución
      <b>Sistema</b> valida, registra los cambios y muestra confirmación
    end note
}

state "DISPENSAS_ABIERTO" as DISPENSAS_ABIERTO

editarSolicitud -[#blue]---> DISPENSAS_ABIERTO
note right on link
  abrirDispensas()
end note
@enduml