@startuml abrirEntregable-analisis
skinparam backgroundColor white
skinparam shadowing false
skinparam DefaultFontColor black
skinparam DefaultFontSize 12
skinparam linetype polyline

rectangle #CDEBA5 "ENTREGABLES_ABIERTOS" as EntregablesAbiertos
rectangle #CDEBA5 "ENTREGABLE_ABIERTO" as EntregableAbierto

package "abrirEntregable()" as abrirEntregable {
    rectangle "DetalleEntregableView" as DetalleEntregableView #629EF9
    rectangle "EntregableController" as EntregableController #b5bd68
    rectangle "EntregableRepository" as EntregableRepository #F2AC4E
    rectangle "Entregable" as Entregable #F2AC4E
}

rectangle #CDEBA5 ":Collaboration EditarEntregable" as EditarEntregable
rectangle #CDEBA5 ":Collaboration EliminarEntregable" as EliminarEntregable
rectangle #CDEBA5 ":Collaboration AbrirEntregables" as AbrirEntregables

EntregablesAbiertos -r-> DetalleEntregableView: abrirEntregable(entregableId)

DetalleEntregableView -d-> EntregableController: obtenerDetalleEntregable(entregableId) : Entregable
EntregableController -d-> EntregableRepository: obtenerPorId(entregableId) : Entregable
EntregableRepository -- Entregable

DetalleEntregableView ..> EditarEntregable: editarEntregable()
DetalleEntregableView ..> EliminarEntregable: eliminarEntregable()
DetalleEntregableView ..> AbrirEntregables: abrirEntregables()

DetalleEntregableView ..> EntregableAbierto: <<finalizar>>

@enduml
