@startuml
skinparam nodesep 60
skinparam ranksep 60
skinparam linetype polyline
skinparam NoteBackgroundColor lightyellow
skinparam NoteBorderColor gray
skinparam StateBackgroundColor #F5F5F5
skinparam StateBorderColor gray

state "abrirAlumnos()" as abrirAlumnos {

    state " " as Paso1
    state " " as Paso2

    [*] -[#green]-> Paso1 
    note on link
      <b>Secretaría</b> solicita abrir alumnos
    end note    
    
    Paso1 -[#green]-> Paso2
    note on link
      <b>Sistema</b> permite mostrar lista de alumnos
      • Nombre, documento, correo, estado
    end note
    
    Paso2 -[#green]-> Paso2
    note on link
      <b>Secretaría</b> solicita filtrar lista
      <b>Sistema</b> permite mostrar lista filtrada
    end note
    
    Paso2 -[#green]-> [*]
    note on link
      <b>Secretaría</b> revisa la lista de alumnos
      <b>Sistema</b> permite mantener la lista en pantalla
      • Permite solicitar consultar alumno
      • Permite solicitar importar alumnos
    end note
}

state "ALUMNO_DETALLE_ABIERTO" as ALUMNO_DETALLE_ABIERTO
state "ALUMNOS_ABIERTO" as ALUMNOS_ABIERTO

abrirAlumnos -[#green]---> ALUMNOS_ABIERTO
note right on link
  importarAlumnos()
end note

abrirAlumnos -[#green]---> ALUMNO_DETALLE_ABIERTO
note right on link
  consultarAlumno()
end note

@enduml
