@startuml
skinparam nodesep 60
skinparam ranksep 60
skinparam linetype polyline
skinparam NoteBackgroundColor lightyellow
skinparam NoteBorderColor gray
skinparam StateBackgroundColor #F5F5F5
skinparam StateBorderColor gray

state "consultarSolicitudDispensa()" as consultarSolicitudDispensa {
   
    state " " as Paso1
    state " " as Paso2
   
    [*] -[#green]-> Paso1
    note on link
      <b>Secretaría</b> solicita mostrar solicitud de dispensa
    end note
   
    Paso1 -[#green]-> Paso2
    note on link
      <b>Sistema</b> muestra los datos de la solicitud:
      • Estado de la Dispensa, Asignatura y Tipo/Motivo
      • Día(s) de la semana y Franja horaria afectada
      • Asignatura solapada y Justificación / Comentarios
    end note
   
    Paso2 -[#green]-> [*]
    note on link
      <b>Secretaría</b> revisa la información de la solicitud
      • Permite solicitar editar solicitud
      • Permite solicitar regresar al listado
    end note
}

state "SOLICITUD_DISPENSA_ABIERTA" as SOLICITUD_DISPENSA_ABIERTA
state "DISPENSAS_ABIERTO" as DISPENSAS_ABIERTO

consultarSolicitudDispensa -[#green]---> SOLICITUD_DISPENSA_ABIERTA
note right on link
  editarSolicitudDispensa()
end note

consultarSolicitudDispensa -[#blue]---> DISPENSAS_ABIERTO
note right on link
  abrirDispensas()
end note
@enduml