@startuml
skinparam nodesep 60
skinparam ranksep 60
skinparam linetype polyline
skinparam NoteBackgroundColor lightyellow
skinparam NoteBorderColor gray
skinparam StateBackgroundColor #F5F5F5
skinparam StateBorderColor gray

state "consultarAlumno()" as consultarAlumno {
   
    state " " as Paso1
    state " " as Paso2
   
    [*] -[#green]-> Paso1
    note on link
      <b>Secretaría</b> solicita mostrar alumno
    end note
   
    Paso1 -[#green]-> Paso2
    note on link
      <b>Sistema</b> muestra datos del alumno:
      • Nombres Completos y DNI / Pasaporte
      • Correo Institucional y Carrera
    end note
   
    Paso2 -[#green]-> [*]
    note on link
      <b>Secretaría</b> revisa la información del alumno
      • Permite solicitar regresar al listado
      • Permite solicitar cancelar operación
    end note
}

state "ALUMNOS_ABIERTO" as ALUMNOS_ABIERTO

consultarAlumno -[#green]---> ALUMNOS_ABIERTO
note right on link
  abrirAlumnos()
end note

consultarAlumno -[#blue]---> ALUMNOS_ABIERTO
note right on link
  cancelar operación
end note
@enduml
