@startuml
skinparam nodesep 60
skinparam ranksep 60
skinparam linetype polyline
skinparam NoteBackgroundColor lightyellow
skinparam NoteBorderColor gray
skinparam StateBackgroundColor #F5F5F5
skinparam StateBorderColor gray

state "importarMatriculas()" as importarMatriculas {
   
    state " " as Paso1
    state " " as Paso2
   
    [*] -[#green]-> Paso1
    note on link
      <b>Secretaría</b> solicita importar información de matrículas
    end note
   
    Paso1 -[#green]-> Paso2
    note on link
      <b>Sistema</b> permite indicar el Formato Aceptado y
      seleccionar el Archivo de Origen (Excel/CSV)
    end note
   
    Paso2 -[#green]-> [*]
    note on link
      <b>Secretaría</b> adjunta el archivo
      <b>Sistema</b> permite importar datos
      • Permite solicitar confirmar importación
      • Permite solicitar cancelar operación
    end note
}

state "MATRICULAS_ABIERTO" as MATRICULAS_ABIERTO

importarMatriculas -[#green]---> MATRICULAS_ABIERTO
note right on link
  abrirMatriculas
end note

importarMatriculas -[#blue]---> MATRICULAS_ABIERTO
note right on link
  cancelar operacion
end note
@enduml
