@startuml importarConfiguracionGlobal-analisis
skinparam linetype polyline

actor Docente

rectangle #CDEBA5 ":Collaboration importarAlumnos" as ColImAl
rectangle #CDEBA5 ":Collaboration importarPreguntas" as ColImPreg
rectangle #CDEBA5 ":Collaboration importarAsignaturas [abstracto]" as ColImAsig
rectangle #CDEBA5 ":Collaboration importarGrados [abstracto]" as ColImGr

package importarConfiguracionGlobal as "importarConfiguracionGlobal()" {
    rectangle #629EF9 VistaImportConfigGlobal
    rectangle #b5bd68 ControladorImportacion
    rectangle #F2AC4E ConfiguracionGlobal
}

Docente -r-> VistaImportConfigGlobal: importarConfiguracion(archivo, opciones)
VistaImportConfigGlobal -d-> ControladorImportacion: procesarImportacion(archivo, opciones)
ControladorImportacion --> ConfiguracionGlobal: extraerDatos()
ControladorImportacion --> VistaImportConfigGlobal: mostrarValidacion()

Docente --> VistaImportConfigGlobal: confirmarImportacion()
VistaImportConfigGlobal ..> ColImAl: <<include>> importarAlumnos()
VistaImportConfigGlobal ..> ColImPreg: <<include>> importarPreguntas()
VistaImportConfigGlobal ..> ColImAsig: <<include>> importarAsignaturas()
VistaImportConfigGlobal ..> ColImGr: <<include>> importarGrados()

@enduml
