@startuml crearProyecto
skinparam linetype polyline

state in1 as "PROYECTOS_ABIERTOS"
in1 -[#green]-> crearProyecto

state crearProyecto as "crearProyecto()" {

    state " " as SolicitandoDatos
    state " " as RegistrandoProyecto

    [*] -[#green]-> SolicitandoDatos
    note on link
    <b>Coordinador</b> solicita crear un nuevo proyecto
    end note

    SolicitandoDatos -[#green]-> RegistrandoProyecto
    note on link
    <b>Sistema</b> presenta el formulario de creación del proyecto y permite introducir:
    • Título
    • Estado inicial
    • Fecha de inicio
    • Fecha de fin
    • Descripción
    <i>El ID del proyecto se genera automáticamente

    y permite solicitar las siguientes acciones:
    • Crear proyecto
    • Volver
    end note

    RegistrandoProyecto -[#green]-> [*]
    note on link
    <b>Coordinador</b> introduce los datos solicitados
    <b>Sistema</b> registra el nuevo proyecto
    end note
}

crearProyecto -[#green]-> PROYECTO_ABIERTO
note on link
Proyecto creado y abierto
end note

crearProyecto -[#green]-> PROYECTO_ABIERTO
note on link
editarProyecto()
end note

crearProyecto -[#green]-> PROYECTOS_ABIERTOS
note on link
eliminarProyecto()
end note

crearProyecto -[#green]-> PROYECTO_ABIERTO
note on link
agregarInvestigador()
end note

crearProyecto -[#green]-> PROYECTO_ABIERTO
note on link
eliminarInvestigador()
end note

crearProyecto -[#green]-> ENTREGABLES_ABIERTOS
note on link
abrirEntregables()
end note

crearProyecto -[#green]-> INVESTIGADORES_ABIERTOS
note on link
abrirInvestigadores()
end note

crearProyecto -[#green]-> PROYECTOS_ABIERTOS
note on link
abrirProyectos()
end note

@enduml