CREATE TABLE convocatorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(220) NOT NULL,
    entidad_convocante VARCHAR(180) NOT NULL,
    area VARCHAR(160) NOT NULL,
    estado VARCHAR(40) NOT NULL,
    fecha_apertura DATE,
    fecha_cierre DATE,
    descripcion VARCHAR(4000) NOT NULL,
    requisitos VARCHAR(4000) NOT NULL,
    criterios_evaluacion VARCHAR(3000) NOT NULL,
    dotacion VARCHAR(180) NOT NULL,
    contacto VARCHAR(240) NOT NULL,
    referencia_externa VARCHAR(500) NOT NULL UNIQUE,
    tipo_fuente VARCHAR(30) NOT NULL,
    incorporada BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_importacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    importada_por_id BIGINT REFERENCES usuarios(id)
);

CREATE INDEX idx_convocatorias_fecha_cierre ON convocatorias(fecha_cierre);
CREATE INDEX idx_convocatorias_area ON convocatorias(area);
CREATE INDEX idx_convocatorias_estado ON convocatorias(estado);

INSERT INTO convocatorias (
    titulo, entidad_convocante, area, estado, fecha_apertura, fecha_cierre,
    descripcion, requisitos, criterios_evaluacion, dotacion, contacto,
    referencia_externa, tipo_fuente, incorporada
) VALUES
(
    'Ayudas a proyectos de investigacion aplicada 2026',
    'FUNIBER',
    'Innovacion y transferencia',
    'ABIERTA',
    DATE '2026-05-15',
    DATE '2026-07-31',
    'Financiacion para proyectos de investigacion aplicada con impacto internacional.',
    'Equipo investigador activo y memoria tecnica.',
    'Impacto, viabilidad y colaboracion internacional.',
    'Hasta 45.000 EUR',
    'convocatorias@funiber.org',
    'demo:funiber-aplicada-2026',
    'ENLACE',
    TRUE
),
(
    'Programa iberoamericano de movilidad investigadora',
    'Fundacion Universitaria Iberoamericana',
    'Movilidad',
    'PROXIMA',
    DATE '2026-08-01',
    DATE '2026-10-15',
    'Apoyo a estancias breves de investigacion entre sedes iberoamericanas.',
    'Vinculacion con un proyecto activo y carta de acogida.',
    'Trayectoria, adecuacion de la estancia y resultados previstos.',
    'Viaje y estancia',
    'movilidad@funiber.org',
    'demo:movilidad-iberoamericana-2026',
    'ARCHIVO',
    TRUE
);
