ALTER TABLE usuarios ADD COLUMN nombre_completo VARCHAR(120);
ALTER TABLE usuarios ADD COLUMN email VARCHAR(120);
ALTER TABLE usuarios ADD COLUMN unidad VARCHAR(120);
ALTER TABLE usuarios ADD COLUMN linea_investigacion VARCHAR(160);
ALTER TABLE usuarios ADD COLUMN biografia VARCHAR(500);

UPDATE usuarios
SET nombre_completo = 'Coordinador FUNIBER',
    email = 'coordinador@funiber.org',
    unidad = 'Coordinación de investigación',
    linea_investigacion = 'Gestión académica e investigación',
    biografia = 'Perfil coordinador con acceso a gestión global de la plataforma.'
WHERE nombre_usuario = 'coordinador';

UPDATE usuarios
SET nombre_completo = 'Investigador FUNIBER',
    email = 'investigador@funiber.org',
    unidad = 'Investigación',
    linea_investigacion = 'Producción científica',
    biografia = 'Perfil investigador con acceso a sus proyectos, publicaciones y entregables.'
WHERE nombre_usuario = 'investigador';

CREATE TABLE solicitudes_eliminacion_perfil (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    motivo VARCHAR(500) NOT NULL,
    estado VARCHAR(30) NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL,
    CONSTRAINT fk_solicitud_eliminacion_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);
