ALTER TABLE usuarios ADD COLUMN sede VARCHAR(30) DEFAULT 'GLOBAL' NOT NULL;

CREATE TABLE cargas_trabajo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL UNIQUE,
    horas_docencia DECIMAL(5, 2) NOT NULL DEFAULT 0,
    horas_investigacion DECIMAL(5, 2) NOT NULL DEFAULT 0,
    horas_gestion_academica DECIMAL(5, 2) NOT NULL DEFAULT 0,
    observaciones VARCHAR(500),
    fecha_actualizacion TIMESTAMP NOT NULL,
    CONSTRAINT fk_carga_trabajo_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

CREATE TABLE recompensas_carga_trabajo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    horas_exceso DECIMAL(5, 2) NOT NULL,
    descripcion VARCHAR(500) NOT NULL,
    estado VARCHAR(30) NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL,
    CONSTRAINT fk_recompensa_carga_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

UPDATE usuarios SET sede = 'GLOBAL' WHERE rol = 'COORDINADOR';
UPDATE usuarios SET sede = 'BARCELONA' WHERE rol = 'INVESTIGADOR';
