CREATE TABLE proyectos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(40) NOT NULL UNIQUE,
    nombre VARCHAR(180) NOT NULL,
    estado VARCHAR(30) NOT NULL
);

CREATE TABLE proyecto_investigadores (
    proyecto_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    PRIMARY KEY (proyecto_id, usuario_id),
    CONSTRAINT fk_proyecto_investigador_proyecto
        FOREIGN KEY (proyecto_id) REFERENCES proyectos(id),
    CONSTRAINT fk_proyecto_investigador_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

CREATE TABLE recompensas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proyecto_id BIGINT NOT NULL,
    beneficiario_id BIGINT NOT NULL,
    tipo VARCHAR(30) NOT NULL,
    concepto VARCHAR(240) NOT NULL,
    valor DECIMAL(10, 2) NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL,
    CONSTRAINT uq_recompensa_proyecto_beneficiario_tipo
        UNIQUE (proyecto_id, beneficiario_id, tipo),
    CONSTRAINT fk_recompensa_proyecto
        FOREIGN KEY (proyecto_id) REFERENCES proyectos(id),
    CONSTRAINT fk_recompensa_beneficiario
        FOREIGN KEY (beneficiario_id) REFERENCES usuarios(id)
);
