ALTER TABLE proyectos ADD COLUMN descripcion VARCHAR(1000);
ALTER TABLE proyectos ADD COLUMN area VARCHAR(120);
ALTER TABLE proyectos ADD COLUMN sede VARCHAR(30);
ALTER TABLE proyectos ADD COLUMN fecha_inicio DATE;
ALTER TABLE proyectos ADD COLUMN fecha_fin DATE;
ALTER TABLE proyectos ADD COLUMN coordinador_id BIGINT;
ALTER TABLE proyectos ADD COLUMN archivado BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE proyectos ADD COLUMN fecha_archivado TIMESTAMP;
ALTER TABLE proyectos ADD COLUMN archivado_por_id BIGINT;
ALTER TABLE proyectos ADD COLUMN motivo_archivado VARCHAR(500);

ALTER TABLE proyectos ADD CONSTRAINT fk_proyecto_coordinador
    FOREIGN KEY (coordinador_id) REFERENCES usuarios(id);
ALTER TABLE proyectos ADD CONSTRAINT fk_proyecto_archivado_por
    FOREIGN KEY (archivado_por_id) REFERENCES usuarios(id);

CREATE TABLE movimientos_participacion_proyecto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proyecto_id BIGINT NOT NULL,
    investigador_id BIGINT NOT NULL,
    tipo VARCHAR(30) NOT NULL,
    responsable_id BIGINT NOT NULL,
    fecha TIMESTAMP NOT NULL,
    motivo VARCHAR(500),
    CONSTRAINT fk_movimiento_proyecto FOREIGN KEY (proyecto_id) REFERENCES proyectos(id),
    CONSTRAINT fk_movimiento_investigador FOREIGN KEY (investigador_id) REFERENCES usuarios(id),
    CONSTRAINT fk_movimiento_responsable FOREIGN KEY (responsable_id) REFERENCES usuarios(id)
);
