CREATE TABLE archivos_proyecto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proyecto_id BIGINT NOT NULL,
    nombre VARCHAR(240) NOT NULL,
    tipo_contenido VARCHAR(160) NOT NULL,
    tamano BIGINT NOT NULL,
    subido_por_id BIGINT NOT NULL,
    fecha_subida TIMESTAMP NOT NULL,
    contenido BYTEA NOT NULL,
    CONSTRAINT fk_archivo_proyecto FOREIGN KEY (proyecto_id) REFERENCES proyectos(id),
    CONSTRAINT fk_archivo_subido_por FOREIGN KEY (subido_por_id) REFERENCES usuarios(id)
);
