@startuml importarGrados-analisis
skinparam linetype polyline

note "<<abstracto>>\nInvocado desde CU-03: importarConfiguracionGlobal" as N1

rectangle #CDEBA5 ":Collaboration crearGrado" as ColCrearGr

package importarGrados as "importarGrados()" {
    rectangle #629EF9 VistaImportacionGrados
    rectangle #b5bd68 ControladorImportacionGrados
    rectangle #F2AC4E Grado
}

VistaImportacionGrados -d-> ControladorImportacionGrados: importarGrados(listaGrados)
ControladorImportacionGrados --> Grado: validarDuplicado()
ControladorImportacionGrados --> VistaImportacionGrados: confirmacion

VistaImportacionGrados ..> ColCrearGr: <<include>> crearGrado() [por cada grado nuevo]

@enduml
