@startuml consultarListaAlumnosSecretaria-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":Listas Abierto" as ListasAbierto

package consultarListaAlumnosSecretaria as "consultarListaAlumnos() [Secretaria]" {
    rectangle #629EF9 ConsultarListaAlumnosSecretariaView
    rectangle #b5bd68 AlumnoController
    rectangle #F2AC4E AlumnoRepository
    rectangle #F2AC4E Alumno
}

ListasAbierto -r-> ConsultarListaAlumnosSecretariaView : consultarListaAlumnos()

ConsultarListaAlumnosSecretariaView -d-> AlumnoController : cargarTodos() : List<Alumno>

AlumnoController --> AlumnoRepository                    : obtenerTodos() : List<Alumno>

AlumnoRepository -- Alumno

@enduml
