@startuml
skinparam style strictuml
title Diagrama de Estados: Matrícula

[*] --> Vigente : importarMatriculas()


Vigente --> Historica : cerrarCicloAcademico()

Vigente --> Vigente : consultarDetalleMatricula()
Historica --> Historica : consultarDetalleMatricula()

Historica --> [*]
@enduml