@startuml cerrarSesion-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":SISTEMA_DISPONIBLE" as SistemaDisponible
rectangle #CDEBA5 ":SESION_CERRADA" as SesionCerrada

package cerrarSesion as "cerrarSesion()" {
    rectangle #629EF9 CerrarSesionView
    rectangle #b5bd68 CerrarSesionController
    rectangle #F2AC4E Sesion
}

SistemaDisponible --> CerrarSesionView: cerrarSesion(usuario)

CerrarSesionView -d-> CerrarSesionController: cerrarSesion(usuario)

CerrarSesionController --> Sesion: <<destroy>> eliminarSesion(usuario)

CerrarSesionView ..> SesionCerrada: sesionCerrada()
CerrarSesionView ..> SistemaDisponible: cancelar()

@enduml
