@startuml cerrarSesion-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":Sistema Disponible" as SistemaDisponible
package cerrarSesion as "cerrarSesion()" {
    rectangle #629EF9 CerrarSesionView
    rectangle #b5bd68 AuthController
}

rectangle #CDEBA5 ":SESION_CERRADA" as SESIONCERRADA

SistemaDisponible -r-> CerrarSesionView: cerrarSesion(Usuario)

CerrarSesionView -d-> AuthController: confirmarCierre(Usuario)

CerrarSesionView ..> SistemaDisponible: cancelarCierre()
CerrarSesionView ..r.> SESIONCERRADA: confirmarCierre()

@enduml