@startuml iniciarSesion-analisis
skinparam linetype polyline

actor UsuarioNoRegistrado
package iniciarSesion as "iniciarSesion()" {
    rectangle #629EF9 LoginView
    rectangle #b5bd68 AuthController
    rectangle #F2AC4E UsuarioRepository
    rectangle #F2AC4E Usuario
}
rectangle #CDEBA5 ":Sistema Disponible" as SistemaDisponible
rectangle #CDEBA5 ":Sesión Cerrada" as SesionCerrada

UsuarioNoRegistrado -r-> SesionCerrada: Docente/Administrador

SesionCerrada -r-> LoginView: iniciarSesion(usuario, contraseña)

LoginView -d-> AuthController: autenticar(usuario, contraseña) : Sesion

AuthController --> UsuarioRepository: validarCredenciales(usuario, contraseña) : Usuario

UsuarioRepository -- Usuario

LoginView -r-> SistemaDisponible: sistemaDisponible(docente | administrador)

@enduml