@startuml iniciarSesion-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":SESION_CERRADA" as SesionCerrada
rectangle #CDEBA5 ":SISTEMA_DISPONIBLE" as SistemaDisponible

package iniciarSesion as "iniciarSesion()" {
    rectangle #629EF9 IniciarSesionView
    rectangle #b5bd68 SesionController
    rectangle #F2AC4E UsuarioRepository
    rectangle #F2AC4E Usuario
    rectangle #F2AC4E Sesion
}

SesionCerrada --> IniciarSesionView: iniciarSesion()

IniciarSesionView -d-> SesionController: autenticar(usuario, contraseña) : boolean

SesionController --> UsuarioRepository: buscarPorCredenciales(usuario, contraseña) : Usuario
UsuarioRepository -- Usuario

SesionController -r-> Sesion: <<create>> crear(usuario)

IniciarSesionView ..> SistemaDisponible: <<include>> [éxito] sistemaDisponible(usuario)

@enduml
