@startuml editarProyecto-analisis
skinparam backgroundColor white
skinparam shadowing false
skinparam DefaultFontColor black
skinparam DefaultFontSize 12
skinparam linetype polyline

rectangle #CDEBA5 "PROYECTO_ABIERTO" as ProyectoAbierto

package "editarProyecto()" as editarProyecto {
    rectangle "EditarProyectoView" as EditarProyectoView #629EF9
    rectangle "ProyectoController" as ProyectoController #b5bd68
    rectangle "ProyectoRepository" as ProyectoRepository #F2AC4E
}

ProyectoAbierto -r-> EditarProyectoView: editarProyecto()

EditarProyectoView -d-> ProyectoController: cargarDatosActuales()
ProyectoController -d-> ProyectoRepository: obtenerPorId(proyectoId) : Proyecto

EditarProyectoView -d-> ProyectoController: guardarCambios(datosNuevos) : boolean
ProyectoController -d-> ProyectoRepository: actualizar(proyecto) : boolean

EditarProyectoView ..> ProyectoAbierto: <<finalizar>> confirmar()
EditarProyectoView ..> ProyectoAbierto: <<cancelar>> cancelar()

@enduml
