@startuml
title "Diagrama de Secuencia - Ver Espacios por Planta (Visitante)"

actor "Visitante" as visitor
boundary "MapaView" as view
entity "MapContext" as context
control "EspacioController" as controller
participant "GestionEspacioService" as service

visitor -> view : Pulsa Tecla 'Tab'
activate view

view -> context : setPlantaIndex(next)
view -> context : cargarDatos()
activate context

context -> controller : obtenerUniversidad()
activate controller

controller -> service : obtenerUniversidad()
activate service

' El servicio llama al Repositorio para cargar universidad.json
service --> controller : Universidad
deactivate service

controller --> context : Universidad
deactivate controller

context --> view : (datos cargados)
deactivate context

view -> context : getCurrentEspacios()
activate context
context --> view : List<Espacio>
deactivate context

view --> visitor : Renderiza la nueva planta con sus espacios
deactivate view

@enduml
