@startuml abrirAlumnos-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":Sistema Disponible" as SistemaDisponible
package abrirAlumnos as "abrirAlumnos()" {
    rectangle #629EF9 AbrirAlumnosView
    rectangle #b5bd68 AlumnosController
    rectangle #F2AC4E AlumnoRepository
    rectangle #F2AC4E Alumno
}

rectangle #CDEBA5 ":Collaboration CrearAlumno" as CrearAlumno
rectangle #CDEBA5 ":Collaboration EditarAlumno" as EditarAlumno
rectangle #CDEBA5 ":Collaboration EliminarAlumno" as EliminarAlumno
rectangle #CDEBA5 ":Collaboration ImportarAlumnos" as ImportarAlumnos

SistemaDisponible -r-> AbrirAlumnosView : abrirAlumnos()

AbrirAlumnosView -d-> AlumnosController: listarAlumnos()
AbrirAlumnosView -d-> AlumnosController: filtrarAlumnos(criterio)

AlumnosController -r-> AlumnoRepository: obtenerTodos()
AlumnosController -r-> AlumnoRepository: buscarPorCriterio(criterio)

AlumnoRepository -d-> Alumno: <<accede>>

AbrirAlumnosView -r-> SistemaDisponible: completarGestion()

AbrirAlumnosView ..> CrearAlumno: crearAlumno()
AbrirAlumnosView ..> EditarAlumno: editarAlumno(Alumno)
AbrirAlumnosView ..> EliminarAlumno: eliminarAlumno(Alumno)
AbrirAlumnosView ..> ImportarAlumnos: importarAlumnos()

@enduml
