@startuml cerrarSesion-analisis
skinparam linetype polyline
left to right direction

actor Usuario
boundary NavbarView
control SesionController
rectangle ":Sesión Cerrada" as SesionCerrada #FFB3BA

Usuario --> NavbarView : 1: cerrarSesion()
NavbarView --> SesionController : 2: finalizarSesion(usuario)
SesionController --> SesionCerrada : 3: actualizaEstado()

@enduml
