@startuml responderPublicacion-analisis
skinparam backgroundColor white
skinparam shadowing false
skinparam DefaultFontColor black
skinparam DefaultFontSize 12
skinparam linetype polyline

rectangle #CDEBA5 "PUBLICACION_ABIERTA" as PublicacionAbierta

package "responderPublicacion()" as responderPublicacion {
    rectangle "ResponderPublicacionView" as ResponderPublicacionView #629EF9
    rectangle "PublicacionController" as PublicacionController #b5bd68
    rectangle "PublicacionRepository" as PublicacionRepository #F2AC4E
    rectangle "Publicacion" as Publicacion #F2AC4E
    rectangle "Sesion" as Sesion #F2AC4E
}

PublicacionAbierta -r-> ResponderPublicacionView: responderPublicacion(publicacionPadreId)

ResponderPublicacionView -d-> PublicacionController: enviarRespuesta(contenido) : boolean
PublicacionController -d-> Sesion: getUsuarioActual() : Usuario
PublicacionController -r-> Publicacion: <<create>> (contenido, autor, padreId)
PublicacionController -d-> PublicacionRepository: guardar(respuesta) : boolean

ResponderPublicacionView ..> PublicacionAbierta: <<finalizar>>
ResponderPublicacionView ..> PublicacionAbierta: <<cancelar>>

@enduml
