@startuml
skinparam nodesep 60
skinparam ranksep 60
skinparam linetype polyline
skinparam NoteBackgroundColor lightyellow
skinparam NoteBorderColor gray
skinparam StateBackgroundColor #F5F5F5
skinparam StateBorderColor gray

state "crearSolicitudDispensa()" as crearSolicitudDispensa {

    ' Estados anónimos vacíos para simular los pasos
    state " " as Paso1
    state " " as Paso2

    [*] -[#green]-> Paso1
    note on link
      <b>Alumno</b> solicita crear una dispensa
    end note

    Paso1 -[#green]-> Paso2
    note on link
      <b>Sistema</b> solicita datos iniciales
      • Asignatura de la dispensa y Tipo/Motivo
      • Día(s) de la semana y Franja horaria afectada
      • Asignatura solapada y Justificación
      • Documento adjunto
    end note

    Paso2 -[#green]-> [*]
    note on link
      <b>Alumno</b> proporciona datos iniciales
      <b>Sistema</b> permite instanciar la solicitud
      • Permite solicitar editar la solicitud
      • Permite solicitar cancelar creación
    end note
}

state "SOLICITUD_DISPENSA_ABIERTA" as SOLICITUD_DISPENSA_ABIERTA
state "DISPENSAS_ABIERTO" as DISPENSAS_ABIERTO

crearSolicitudDispensa -[#green]---> SOLICITUD_DISPENSA_ABIERTA
note right on link
  editarSolicitudDispensa()
end note

crearSolicitudDispensa -[#blue]---> DISPENSAS_ABIERTO
note right on link
  cancelar creación
end note

@enduml