@startuml importarConvocatoria
skinparam linetype polyline

state in1 as "CONVOCATORIA_ABIERTA"
in1 -[#green]-> importarConvocatoria

state importarConvocatoria as "importarConvocatoria()" {

    state " " as SolicitandoImportacion
    state " " as IntroduciendoFuente
    state " " as ConfirmandoImportacion

    [*] -[#green]-> SolicitandoImportacion
    note on link
    <b>Coordinador</b> solicita importar la convocatoria
    end note

    SolicitandoImportacion -[#green]-> IntroduciendoFuente
    note on link
    <b>Sistema</b> presenta la opción de importación
    <b>Sistema</b> permite introducir la fuente de importación:
    • Archivo (PDF / DOC / XLS)
    • Enlace externo

    <b>Sistema</b> muestra información a incorporar (si aplica):
    • Título
    • Área
    • Estado
    • Fechas relevantes
    • Descripción
    • Requisitos y condiciones
    • Criterios de evaluación y dotación
    • Documentación asociada
    • Información de contacto

    <b>Sistema</b> permite solicitar:
    • Importar convocatoria
    • Cancelar
    end note

    IntroduciendoFuente -[#green]-> ConfirmandoImportacion
    note on link
    <b>Coordinador</b> solicita importar la información
    end note

    ConfirmandoImportacion -[#green]-> [*]
    note on link
    <b>Sistema</b> permite solicitar la importación
    <b>Sistema</b> presenta y visualiza la convocatoria con la información importada
    end note

    ConfirmandoImportacion -[#red]-> [*]
    note on link
    <b>Coordinador</b> solicita cancelar la importación
    <b>Sistema</b> presenta y visualiza la convocatoria sin cambios
    end note
}

importarConvocatoria -[#green]-> CONVOCATORIA_ABIERTA
note on link
Convocatoria importada
end note

importarConvocatoria -[#red]-> CONVOCATORIA_ABIERTA
note on link
Importación cancelada
end note

@enduml
