CREATE TABLE IF NOT EXISTS Preferencia (
  id INT AUTO_INCREMENT PRIMARY KEY,
  diaSemana INT NOT NULL,
  horaInicio VARCHAR(5) NOT NULL,
  horaFin VARCHAR(5) NOT NULL,
  disponible TINYINT(1) DEFAULT 1,
  profesorId INT NOT NULL,
  fechaCreacion DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
  fechaActualizacion DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT FK_Preferencia_Profesor FOREIGN KEY (profesorId) REFERENCES Profesor(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
