@startsalt eliminarRecompensa-wireframe
{
    ====
    <b>GIPF - ELIMINAR RECOMPENSA</b>
    ====
    {
        <b>Confirmación de anulación</b>
        --
        {
            "¿Está seguro de que desea eliminar esta recompensa?"
        }

        ~~

        {[Confirmar] | [Cancelar]}

        ~~

        <b>Resultado</b>
        --
        {
            "La recompensa ha sido anulada correctamente."
        }
    }
}
@endsalt
