@startuml eliminarGrupo-analisis
skinparam linetype polyline

actor Usuario
package eliminarGrupo as "eliminarGrupo()" {
    rectangle #629EF9 ListarGruposView
    rectangle #b5bd68 GruposController
    rectangle #F2AC4E GrupoRepository
    rectangle #F2AC4E Grupo
    rectangle #F2AC4E MiembroGrupo
    rectangle #F2AC4E Invitacion
}
rectangle #CDEBA5 ":Sistema Disponible" as SistemaDisponible

SistemaDisponible -r-> ListarGruposView: 1: eliminarGrupo(grupo)

ListarGruposView -d-> GruposController: 2: procesarEliminacion(idGrupo)

GruposController --> GrupoRepository: 3: eliminarGrupoCascada(idGrupo)

GrupoRepository -- Grupo
GrupoRepository -- MiembroGrupo
GrupoRepository -- Invitacion

ListarGruposView -r-> SistemaDisponible: 4: sistemaDisponible(usuario)

@enduml
