@startuml editarAsignatura-analisis
skinparam linetype polyline

actor Docente
package editarAsignatura as "editarAsignatura()" {
    rectangle #629EF9 VistaEdicionAsignatura
    rectangle #b5bd68 ControladorAsignaturas
    rectangle #F2AC4E Asignatura
    rectangle #F2AC4E Grado
    rectangle #F2AC4E Alumno
    rectangle #F2AC4E Pregunta
}

Docente -r-> VistaEdicionAsignatura: modificarDatos(datos)
VistaEdicionAsignatura -d-> ControladorAsignaturas: guardar(datos)
ControladorAsignaturas --> Asignatura: actualizar(datos)

Docente --> VistaEdicionAsignatura: verBateriaPreguntas()
VistaEdicionAsignatura --> ControladorAsignaturas: abrirPreguntas()

Docente --> VistaEdicionAsignatura: eliminarAsignatura()
VistaEdicionAsignatura --> ControladorAsignaturas: eliminar()
ControladorAsignaturas --> Asignatura: delete()

@enduml