@startuml abrirExamenes-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":Sistema Disponible" as SistemaDisponible

package abrirExamenes as "abrirExamenes()" {
    rectangle #629EF9 ListarExamenesView
    rectangle #b5bd68 ExamenController
    rectangle #F2AC4E ExamenRepository
    rectangle #F2AC4E Examen
}

rectangle #CDEBA5 ":Sistema Disponible" as SistemaDisponibleSalida
rectangle #CDEBA5 ":Collaboration CrearExamen" as CrearExamen
rectangle #CDEBA5 ":Collaboration EditarExamen" as EditarExamen
rectangle #CDEBA5 ":Collaboration EliminarExamen" as EliminarExamen

SistemaDisponible -r-> ListarExamenesView: abrirExamenes()

ListarExamenesView -d-> ExamenController: listarExamenes(pagina) : PagedResult<Examen>

ExamenController --> ExamenRepository: obtenerPaginados(pagina) : PagedResult<Examen>

ExamenRepository -- Examen

ListarExamenesView --> ExamenController: filtrarExamenes(criterio, pagina) : PagedResult<Examen>

ExamenController --> ExamenRepository: buscarPaginados(criterio, pagina) : PagedResult<Examen>

ListarExamenesView ..> SistemaDisponibleSalida: completarGestion()
ListarExamenesView ..> CrearExamen: crearExamen()
ListarExamenesView ..> EditarExamen: editarExamen()
ListarExamenesView ..> EliminarExamen: eliminarExamen()

@enduml
