@startuml verExamen-analisis
skinparam linetype polyline

actor Docente
package verExamen as "verExamen()" {
    rectangle #629EF9 VistaDetalleAlumno
    rectangle #629EF9 ExamenRevisionPage
    rectangle #b5bd68 ControladorExamen
    rectangle #F2AC4E ExamenAlumno
    rectangle #F2AC4E Pregunta
}

note "ExamenRevisionPage se abre\nen una nueva pestaña del navegador" as N1

Docente -r-> VistaDetalleAlumno: seleccionarExamen(ejemplarId)
VistaDetalleAlumno -r-> ExamenRevisionPage: abrirNuevaPestana(ejemplarId)
ExamenRevisionPage -d-> ControladorExamen: obtenerRevision(ejemplarId)
ControladorExamen --> ExamenAlumno: obtenerConPreguntas(id)
ControladorExamen --> Pregunta: obtenerRespuestas()
ControladorExamen --> ExamenRevisionPage: datosRevision

@enduml
