@startuml verRespuestas-analisis
skinparam linetype polyline

actor Docente
package verRespuestas as "verRespuestas()" {
    rectangle #629EF9 VistaListaRespuestas
    rectangle #b5bd68 ControladorConsultaRespuestas
    rectangle #F2AC4E Respuesta
    rectangle #F2AC4E Pregunta
}

Docente -r-> VistaListaRespuestas: solicitarVerRespuestas()
VistaListaRespuestas --> ControladorConsultaRespuestas: getRespuestas()
ControladorConsultaRespuestas --> Respuesta: find()
ControladorConsultaRespuestas --> Pregunta: getDatos()
Docente --> VistaListaRespuestas: solicitarFiltro()
VistaListaRespuestas --> ControladorConsultaRespuestas: filtrar()

@enduml