spring.datasource.url=jdbc:postgresql://localhost:5432/jorgestor
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Actuator
management.endpoints.web.exposure.include=mappings,health
management.endpoint.mappings.show-details=always

# JWT Config (para uso posterior en AuthService)
jorgestor.jwt.secret=mi_clave_secreta_muy_larga_y_segura_para_el_proyecto_jorgestor_2026
jorgestor.jwt.expiration=86400000
