spring.datasource.url=jdbc:h2:file:./data/funiber;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

server.servlet.session.cookie.secure=false

