@startuml crearInvestigador

skinparam linetype polyline

state in1 as "INVESTIGADORES_ABIERTOS"
in1 -[#green]-> crearInvestigador
note on link
crearInvestigador()
end note

state crearInvestigador as "crearInvestigador()" {

    state " " as SolicitandoDatos
    state " " as CreandoInvestigador

    [*] -[#green]-> SolicitandoDatos 
    note on link
    <b>Coordinador</b> solicita crear investigador nuevo
    end note    
    
    SolicitandoDatos -[#green]-> CreandoInvestigador
    note on link
    <b>Sistema</b> presenta solicitud de datos mínimos del investigador
    • ID del investigador (obligatorio)
    • Nombre del investigador (obligatorio)
    • Campo del investigador (obligatorio)
    • Permite solicitar crear investigador
    • Permite solicitar cancelar creación
    end note
    
    CreandoInvestigador -[#green]-> [*]
    note on link
    <b>Coordinador</b> proporciona datos mínimos
    <b>Sistema</b> crea investigador y transfiere a edición
    end note
}


crearInvestigador -[#green]-> INVESTIGADOR_ABIERTO
note on link
Investigador creado
end note

crearInvestigador -[#green]-> OPCIONES_PERFIL_ABIERTO
note on link
abrirOpcionesPerfil()
end note

crearInvestigador -[#red]-> INVESTIGADORES_ABIERTOS
note on link
Creación cancelada
end note

@enduml
