@startuml abrirRecompensas-analisis
skinparam backgroundColor white
skinparam shadowing false
skinparam DefaultFontColor black
skinparam DefaultFontSize 12
skinparam linetype polyline

rectangle #CDEBA5 "Navegación Sistema" as NavegacionSistema
rectangle #CDEBA5 "RECOMPENSAS_ABIERTAS" as RecompensasAbiertas

package "abrirRecompensas()" as abrirRecompensas {
    rectangle "ListarRecompensasView" as ListarRecompensasView #629EF9
    rectangle "RecompensaController" as RecompensaController #b5bd68
    rectangle "RecompensaRepository" as RecompensaRepository #F2AC4E
    rectangle "Recompensa" as Recompensa #F2AC4E
}

rectangle #CDEBA5 ":Collaboration AbrirRecompensa" as AbrirRecompensa
rectangle #CDEBA5 ":Collaboration CrearRecompensa" as CrearRecompensa
rectangle #CDEBA5 ":Collaboration AbrirPanelPrincipal" as AbrirPanelPrincipal

NavegacionSistema -r-> ListarRecompensasView: abrirRecompensas()

ListarRecompensasView -d-> RecompensaController: listarRecompensas() : List<Recompensa>
RecompensaController -d-> RecompensaRepository: obtenerTodas() : List<Recompensa>
RecompensaRepository -- Recompensa

ListarRecompensasView ..> AbrirRecompensa: abrirRecompensa(recompensaId)
ListarRecompensasView ..> CrearRecompensa: crearRecompensa()
ListarRecompensasView ..> AbrirPanelPrincipal: abrirPanelPrincipal()

ListarRecompensasView ..> RecompensasAbiertas: <<finalizar>>

@enduml
