@startuml
title "Diagrama de Secuencia - Crear Región"

actor "Administrador" as admin
boundary "MapaView" as view
boundary "ConfigDialog" as config
boundary "DialogForm" as form
control "EspacioController" as controller

admin -> view: Pulsa tecla "O" (Config)
activate view
view -> config: show()
activate config

admin -> config: Pulsa tecla "A" (Add Region)
config -> form: showForm("Add Region")
activate form
form --> config: [Nombre]
deactivate form

config -> controller: agregarRegion(nombre)
activate controller
controller -> controller: Crear objeto Region (UUID)
controller -> controller: Añadir a Universidad y Guardar
controller --> config: ok
deactivate controller

config --> admin: Lista de regiones actualizada
deactivate config
deactivate view

@enduml