@startuml
title "Diagrama de Secuencia - Cambiar de Espacio (En Recorrido)"

actor "Visitante" as visitor
boundary "MapaView" as view
control "VisitaController" as controller
control "VisitaService" as service
entity "Visita" as visit

visitor -> view: Pulsa "Flecha Izquierda" o "Flecha Derecha"
activate view
view -> controller: cambiarEspacio(direccion)
activate controller
controller -> service: cambiarEspacio(direccion)
activate service
service -> visit: getCurrentRecorridoId()
service -> visit: setCurrentEspacioId(nuevoId)
service --> controller: Espacio
deactivate service
controller --> view: Nuevo espacio actual
deactivate controller
view --> visitor: Actualiza cursor del mapa al nuevo espacio
deactivate view

@enduml
