@startsalt importarConvocatoria-wireframe
{
    ====
    <b>GIPF - IMPORTAR CONVOCATORIA</b>
    ====

    <b>Fuente de importación</b>
    --
    {
        { <b>Archivo (opcional):</b> | [ Seleccionar archivo ] }
        --
        { <b>Enlace externo (opcional):</b> | [                              ] }
    }

    ~~

    <b>Información general</b>
    --
    {
        { <b>Título:</b> | [                                      ] }
        --
        { <b>Área:</b> | [                    ] }
        --
        { <b>Estado:</b> | { "Abierta" | "Borrador" } }
        --
        { <b>Apertura:</b> | [            ] }
        --
        { <b>Cierre:</b> | [                      ] }
        --
        { <b>Publica:</b> | [                              ] }
    }

    ~~

    <b>Descripción</b>
    --
    {
        {[                                                        ]}
    }

    ~~

    <b>Requisitos</b>
    --
    {
        {[                                                        ]}
    }

    ~~

    <b>Dotación y condiciones</b>
    --
    {
        {[                                                        ]}
    }

    ~~

    <b>Criterios de evaluación</b>
    --
    {
        {[                                                        ]}
    }

    ~~

    <b>Presentación de propuestas</b>
    --
    {
        {[                                                        ]}
    }

    ~~

    <b>Documentación</b>
    --
    {
        { "📎 Añadir documento" | [Añadir] }
        { "📎 Añadir plantilla" | [Añadir] }
        { "📎 Añadir anexo" | [Añadir] }
    }

    ~~

    <b>Contacto</b>
    --
    {
        { <b>Email:</b> | [                 ] }
        --
        { <b>Horario:</b> | [             ] }
    }

    --

    <i>El ID de la convocatoria se genera automáticamente</i>
    <i>Tras la importación, la convocatoria permanecerá abierta y se visualiza actualizada</i>

    --

    { [Importar convocatoria] | [Cancelar] }
}
@endsalt

