@startuml editarInvitacion-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":Estado origen SdR" as EstadoOrigen
rectangle #CDEBA5 ":Estado destino SdR" as EstadoDestino

package "editarInvitacion()" {
    rectangle #629EF9 EditarInvitacionView
    rectangle #b5bd68 EditarInvitacionController
    rectangle #F2AC4E RepositorioDominio
    rectangle #F2AC4E EntidadDominio
}

EstadoOrigen --> EditarInvitacionView: editarInvitacion()
EditarInvitacionView --> EditarInvitacionController: coordinarCasoUso()
EditarInvitacionController --> RepositorioDominio: consultarOModificarDominio()
RepositorioDominio -- EntidadDominio
EditarInvitacionView --> EstadoDestino: presentaResultado()

@enduml
