@startsalt cerrarSesion-wireframe
{
    ====
    <b>GIPF - Gestor Investigadores y Proyectos de FUNIBER
    ====
    {^ <b>Cerrar sesión
        ¿Desea cerrar la sesión activa?

        Usuario actual: **Coordinador**

        .
        {
            [Cancelar] | [Cerrar sesión]
        }
    }
    ====
    Sistema: Activo
    ====
}
@endsalt
