@startuml abrirPublicaciones
skinparam linetype polyline

state in1 as "PANEL_PRINCIPAL_ABIERTO"
state in2 as "PUBLICACION_ABIERTA"
in1 -[#green]-> abrirPublicaciones : abrirPublicaciones()
in2 -[#green]-> abrirPublicaciones : abrirPublicaciones()

state abrirPublicaciones as "abrirPublicaciones()" {
    state " " as MostrandoListado
    state " " as FiltrandoListado

    [*] -[#green]-> MostrandoListado
    note on link
    <b>Coordinador</b> solicita abrir publicaciones
    <b>Sistema</b> presenta las publicaciones activas con:
    • Titulo
    • Autor
    • Fecha
    • Estado
    end note

    MostrandoListado -[#green]-> FiltrandoListado
    note on link
    <b>Coordinador</b> solicita filtrar el listado
    <b>Sistema</b> presenta las publicaciones activas coincidentes
    end note

    MostrandoListado -[#green]-> [*]
    note on link
    <b>Coordinador</b> selecciona una publicacion
    end note

    FiltrandoListado -[#green]-> [*]
    note on link
    <b>Coordinador</b> selecciona una publicacion
    end note
}

abrirPublicaciones -[#green]-> PUBLICACIONES_ABIERTAS : Listado mostrado
abrirPublicaciones -[#green]-> PUBLICACION_ABIERTA : abrirPublicacion()
abrirPublicaciones -[#green]-> PANEL_PRINCIPAL_ABIERTO : abrirPanelPrincipal()
@enduml
