@startuml

title Modelo de dominio completo

class Alumno
class Matricula
class Asignatura
class Dispensa
class Asistencia
class Profesor
class Grado
class DirectorDeGrado
class SecretariaAcademica 
class SesionDeClase

Alumno --> Matricula : Realiza
Alumno --> Dispensa : Solicita
Matricula --> Grado : Pertenece a
Matricula --> SecretariaAcademica : Gestionada por
Asignatura --> Grado : Pertenece a
Asignatura *-- Alumno : Tiene
Asignatura *-- SesionDeClase : Tiene
Asignatura --> Profesor : Impartida por
SesionDeClase *-- Asistencia : Registra
Asistencia --> Profesor : Realizada por
Dispensa --> SesionDeClase : Exime de
Dispensa --> DirectorDeGrado : Aprobada por
Dispensa --> SecretariaAcademica : Gestionada por
Grado --> DirectorDeGrado : Dirigido por
Grado --> SecretariaAcademica : Gestionado por
DirectorDeGrado -u-|> Profesor : Es un
@enduml
