@startuml crearAsignatura-analisis
skinparam backgroundColor white
skinparam shadowing false
skinparam DefaultFontColor black
skinparam DefaultFontSize 12
skinparam linetype polyline

rectangle #CDEBA5 ":Asignaturas Abierta" as AsignaturasAbierto

package crearAsignatura as "crearAsignatura()" {
    rectangle #629EF9 CrearAsignaturaView
    rectangle #b5bd68 AsignaturaController
    rectangle #F2AC4E AsignaturaRepository
    rectangle #F2AC4E GradoRepository
    rectangle #F2AC4E Asignatura
    rectangle #F2AC4E Grado
}

rectangle #CDEBA5 ":Asignatura Abierto" as AsignaturaAbierto
rectangle #CDEBA5 ":Asignaturas Abierta" as AsignaturasAbiertoSalida

AsignaturasAbierto -r-> CrearAsignaturaView: crearAsignatura()

CrearAsignaturaView -d-> AsignaturaController: obtenerGradosDisponibles() : List<Grado>
AsignaturaController -d-> GradoRepository: obtenerTodos() : List<Grado>

CrearAsignaturaView -d-> AsignaturaController: crear(codigo, nombre, creditos, id_grado) : Asignatura

AsignaturaController -d-> AsignaturaRepository: existeCodigo(codigo) : Boolean
AsignaturaController -r-> Asignatura: <<create>>
AsignaturaController -d-> AsignaturaRepository: guardar(asignatura)

Asignatura -- Grado

CrearAsignaturaView ..> AsignaturaAbierto: <<finalizar>> editarAsignatura(nuevaAsignatura)
CrearAsignaturaView ..> AsignaturasAbiertoSalida: <<cancelar>>

@enduml
