@startuml crearProfesor

skinparam linetype polyline

state crearProfesor as "crearProfesor()" {

state " " as MostrandoFormulario
state " " as GuardandoDatos
state " " as ValidandoDatos

[*] -[#green]-> MostrandoFormulario 
note on link
<b>Administrador</b> solicita crear profesor
end note    

MostrandoFormulario -[#green]-> ValidandoDatos
note on link
<b>Sistema</b> presenta formulario de creación
• Permite introducir código de profesor
• Permite introducir nombre completo
• Permite introducir email
• Permite introducir departamento
• Permite solicitar guardar profesor
• Permite solicitar cancelar creación
end note

ValidandoDatos -[#green]-> GuardandoDatos
note on link
<b>Administrador</b> introduce datos y solicita guardar
<b>Sistema</b> presenta validación de campos requeridos
<b>Sistema</b> presenta validación de que el email sea único
end note

GuardandoDatos -[#green]-> [*]
note on link
<b>Sistema</b> visualiza y guarda el nuevo profesor en la base de datos
end note
}

crearProfesor -[#green]-> PROFESOR_ABIERTO
note on link
editarProfesor()
end note

crearProfesor -[#green]-> PROFESORES_ABIERTO
note on link
abrirProfesores()
end note

@enduml