@startuml eliminarGrado-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":Grados Abierto" as GradosAbierto

package eliminarGrado as "eliminarGrado()" {
    rectangle #629EF9 EliminarGradoView
    rectangle #b5bd68 GradoController
    rectangle #F2AC4E GradoRepository
    rectangle #F2AC4E Grado
}

rectangle #F2AC4E AsignaturaRepository
rectangle #CDEBA5 ":Grados Abierto" as GradosAbiertoSalida

GradosAbierto -r-> EliminarGradoView: eliminarGrado(grado)

EliminarGradoView -d-> GradoController: verificarAsignaturasAsociadas(grado) : Integer

GradoController -d-> AsignaturaRepository: contarPorGrado(grado) : Integer

EliminarGradoView -d-> GradoController: eliminar(grado)

GradoController -d-> GradoRepository: eliminar(grado)

EliminarGradoView ..> GradosAbiertoSalida: <<finalizar>>
EliminarGradoView ..> GradosAbiertoSalida: <<cancelar>>

@enduml
