@startuml eliminarAlumno-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":ALUMNOS_ABIERTO" as AlumnosAbierto
rectangle #CDEBA5 ":ALUMNO_ABIERTO" as AlumnoAbierto
rectangle #CDEBA5 ":Collaboration VerAlumnos" as CollaborationVerAlumnos

package eliminarAlumno as "eliminarAlumno()" {
    rectangle #629EF9 EliminarAlumnoView
    rectangle #b5bd68 AlumnoController
    rectangle #F2AC4E AlumnoRepository
    rectangle #F2AC4E Alumno
}

AlumnosAbierto --> EliminarAlumnoView: eliminarAlumno(id)
AlumnoAbierto --> EliminarAlumnoView: eliminarAlumno(id)

EliminarAlumnoView -d-> AlumnoController: confirmarEliminacion(id) : boolean

AlumnoController --> AlumnoRepository: eliminar(id) : boolean

AlumnoRepository -- Alumno

EliminarAlumnoView ..> CollaborationVerAlumnos: <<include>> verAlumnos()

@enduml
