@startuml crearProyecto-analisis
skinparam backgroundColor white
skinparam shadowing false
skinparam DefaultFontColor black
skinparam DefaultFontSize 12
skinparam linetype polyline

rectangle #CDEBA5 "PROYECTOS_ABIERTOS" as ProyectosAbiertos
rectangle #CDEBA5 "PROYECTO_ABIERTO" as ProyectoAbierto

package "crearProyecto()" as crearProyecto {
    rectangle "CrearProyectoView" as CrearProyectoView #629EF9
    rectangle "ProyectoController" as ProyectoController #b5bd68
    rectangle "ProyectoRepository" as ProyectoRepository #F2AC4E
    rectangle "Proyecto" as Proyecto #F2AC4E
}

ProyectosAbiertos -r-> CrearProyectoView: crearProyecto()

CrearProyectoView -d-> ProyectoController: crear(titulo, estado, f_inicio, f_fin, descripcion) : Proyecto
ProyectoController -r-> Proyecto: <<create>>
ProyectoController -d-> ProyectoRepository: guardar(proyecto)

CrearProyectoView ..> ProyectoAbierto: <<finalizar>> abrirProyecto(proyecto)
CrearProyectoView ..> ProyectosAbiertos: <<cancelar>> abrirProyectos()

@enduml
