@startuml abrirPublicacion-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":PUBLICACIONES_ABIERTAS" as PublicacionesAbiertas

package abrirPublicacion as "abrirPublicacion()" {
    rectangle #629EF9 PublicacionView
    rectangle #b5bd68 PublicacionController
    rectangle #F2AC4E PublicacionRepository
    rectangle #F2AC4E Publicacion
}

rectangle #CDEBA5 ":PUBLICACION_ABIERTA" as PublicacionAbierta
rectangle #CDEBA5 ":Collaboration ResponderPublicacion" as ColResponder
rectangle #CDEBA5 ":Collaboration EditarPublicacion" as ColEditar
rectangle #CDEBA5 ":Collaboration EliminarPublicacion" as ColEliminar
rectangle #CDEBA5 ":PUBLICACIONES_ABIERTAS" as PublicacionesSalida

PublicacionesAbiertas -r-> PublicacionView: abrirPublicacion(id)

PublicacionView -d-> PublicacionController: obtenerPublicacion(id) : Publicacion

PublicacionController --> PublicacionRepository: obtenerPorId(id) : Publicacion

PublicacionRepository -- Publicacion

PublicacionView ..> PublicacionAbierta: publicacionMostrada()
PublicacionView ..> ColResponder: responderPublicacion()
PublicacionView ..> ColEditar: editarPublicacion()
PublicacionView ..> ColEliminar: eliminarPublicacion()
PublicacionView ..> PublicacionesSalida: abrirPublicaciones()

@enduml
