@startuml abrirSolicitudesEliminacionPerfil-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":OPCIONES_PERFIL_INVESTIGADOR_ABIERTO" as OpcionesPerfilEntrada
rectangle #CDEBA5 ":SOLICITUD_ELIMINACION_PERFIL_ABIERTA" as SolicitudAbiertoEntrada

package abrirSolicitudesEliminacionPerfil as "abrirSolicitudesEliminacionPerfil()" {
    rectangle #629EF9 SolicitudesEliminacionView
    rectangle #b5bd68 EliminacionController
    rectangle #F2AC4E SolicitudEliminacionRepository
    rectangle #F2AC4E SolicitudEliminacion
}

rectangle #CDEBA5 ":SOLICITUDES_ELIMINACION_PERFIL_ABIERTAS" as SolicitudesAbiertas
rectangle #CDEBA5 ":Collaboration AbrirSolicitudEliminacionPerfil" as ColSolicitud
rectangle #CDEBA5 ":OPCIONES_PERFIL_INVESTIGADOR_ABIERTO" as OpcionesPerfilSalida

OpcionesPerfilEntrada -r-> SolicitudesEliminacionView: abrirSolicitudesEliminacionPerfil()
SolicitudAbiertoEntrada -r-> SolicitudesEliminacionView: abrirSolicitudesEliminacionPerfil()

SolicitudesEliminacionView -d-> EliminacionController: obtenerSolicitudes() : List<SolicitudEliminacion>

EliminacionController --> SolicitudEliminacionRepository: obtenerTodos() : List<SolicitudEliminacion>

SolicitudEliminacionRepository -- SolicitudEliminacion

SolicitudesEliminacionView ..> SolicitudesAbiertas: solicitudesCargadas()
SolicitudesEliminacionView ..> ColSolicitud: abrirSolicitudEliminacionPerfil(id)
SolicitudesEliminacionView ..> OpcionesPerfilSalida: abrirOpcionesPerfilInvestigador(id)

@enduml
