@startuml cerrarSesion-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":PANEL_PRINCIPAL_ABIERTO" as PanelPrincipal

package cerrarSesion as "cerrarSesion()" {
    rectangle #b5bd68 SesionController
}

rectangle #CDEBA5 ":SESION_CERRADA" as SesionCerrada

PanelPrincipal -r-> SesionController: cerrarSesion()

SesionController ..> SesionCerrada: sesionCerrada()

@enduml
