@startuml editarPublicacion-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":PUBLICACION_ABIERTA" as PublicacionAbierta

package editarPublicacion as "editarPublicacion()" {
    rectangle #629EF9 EditarPublicacionView
    rectangle #b5bd68 PublicacionController
    rectangle #F2AC4E PublicacionRepository
    rectangle #F2AC4E Publicacion
}

rectangle #CDEBA5 ":PUBLICACION_ABIERTA" as PublicacionSalida

PublicacionAbierta -r-> EditarPublicacionView: editarPublicacion()

EditarPublicacionView -d-> PublicacionController: obtenerPublicacion(id) : Publicacion

PublicacionController --> PublicacionRepository: obtenerPorId(id) : Publicacion

PublicacionRepository -- Publicacion

EditarPublicacionView --> PublicacionController: modificarCampos(datos) : void

EditarPublicacionView --> PublicacionController: guardarPublicacion(datos) : Publicacion

PublicacionController --> PublicacionRepository: actualizar(publicacion) : Publicacion

EditarPublicacionView ..> PublicacionSalida: edicionFinalizada()

@enduml
