@startuml eliminarInvestigador-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":PROYECTO_ABIERTO" as ProyectoAbierto

package eliminarInvestigador as "eliminarInvestigador()" {
    rectangle #629EF9 EliminarInvestigadorView
    rectangle #b5bd68 ProyectoController
    rectangle #F2AC4E InvestigadorRepository
    rectangle #F2AC4E Investigador
    rectangle #F2AC4E ProyectoRepository
    rectangle #F2AC4E Proyecto
}

rectangle #CDEBA5 ":PROYECTO_ABIERTO" as ProyectoSalida

ProyectoAbierto -r-> EliminarInvestigadorView: eliminarInvestigador()

EliminarInvestigadorView -d-> ProyectoController: cargarInvestigadorParaEliminacion(idInvestigador) : Investigador

ProyectoController --> InvestigadorRepository: obtenerPorId(idInvestigador) : Investigador

InvestigadorRepository -- Investigador

EliminarInvestigadorView --> ProyectoController: eliminarInvestigador(idProyecto, idInvestigador) : void

ProyectoController --> ProyectoRepository: eliminarInvestigador(idProyecto, idInvestigador) : void

ProyectoRepository -- Proyecto

EliminarInvestigadorView ..> ProyectoSalida: investigadorEliminado()

@enduml
