@startuml iniciarSesion-investigador-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":SESION_CERRADA" as SesionCerrada

package iniciarSesion as "iniciarSesion() — Investigador" {
    rectangle #629EF9 IniciarSesionView
    rectangle #b5bd68 AutenticacionController
    rectangle #F2AC4E InvestigadorRepository
    rectangle #F2AC4E Investigador
}

rectangle #CDEBA5 ":PANEL_PRINCIPAL_ABIERTO" as PanelPrincipal

SesionCerrada -r-> IniciarSesionView: iniciarSesion()

IniciarSesionView -d-> AutenticacionController: autenticar(usuario, contrasena) : boolean

AutenticacionController --> InvestigadorRepository: buscarPorCredenciales(usuario, contrasena) : Investigador

InvestigadorRepository -- Investigador

IniciarSesionView ..> PanelPrincipal: sesionIniciada()
IniciarSesionView ..> IniciarSesionView: credencialesIncorrectas()

@enduml
