@startuml editarRecompensa-analisis
skinparam backgroundColor white
skinparam shadowing false
skinparam DefaultFontColor black
skinparam DefaultFontSize 12
skinparam linetype polyline

rectangle #CDEBA5 "RECOMPENSA_ABIERTA" as RecompensaAbierta

package "editarRecompensa()" as editarRecompensa {
    rectangle "EditarRecompensaView" as EditarRecompensaView #629EF9
    rectangle "RecompensaController" as RecompensaController #b5bd68
    rectangle "RecompensaRepository" as RecompensaRepository #F2AC4E
}

RecompensaAbierta -r-> EditarRecompensaView: editarRecompensa()

EditarRecompensaView -d-> RecompensaController: cargarDatosActuales()
RecompensaController -d-> RecompensaRepository: obtenerPorId(recompensaId) : Recompensa

EditarRecompensaView -d-> RecompensaController: guardarCambios(datosNuevos) : boolean
RecompensaController -d-> RecompensaRepository: actualizar(recompensa) : boolean

EditarRecompensaView ..> RecompensaAbierta: <<finalizar>> confirmar()
EditarRecompensaView ..> RecompensaAbierta: <<cancelar>> cancelar()

@enduml
