@startsalt crearEntregable-wireframe
{
    ====
    <b>GIPF - CREAR ENTREGABLE</b>
    ====
    {
        <b>Datos del entregable</b>
        --
        {
            {
            {<b>Título:</b> | [                                      ]}
            --
            {<b>Tipo:</b> | { "Informe" | "Dataset" | "Presentación" | "Otro" }}
            --
            {<b>Estado inicial:</b> | { "Pendiente" | "En curso" | "Entregado" }}
            --
            {<b>Fecha límite:</b> | [            ]}
            --
            {<b>Descripción (opcional):</b> |
                {[                                      ]}}
            }
            --
            <i>El ID del entregable se genera automáticamente</i>
            <i>Tras crearlo, el entregable se abrirá para continuar su definición</i>
        }

        ~~

        <b>Adjunto (opcional)</b>
        {
            {[ Añadir archivo ] | [ Añadir enlace ]}
        }

        ~~

        {[Crear entregable] | [Volver a entregables]}
    }
}
@endsalt
