@startuml abrirAsignaturas-analisis
skinparam backgroundColor white
skinparam shadowing false
skinparam DefaultFontColor black
skinparam DefaultFontSize 12
skinparam linetype polyline

rectangle #CDEBA5 ":Sistema Disponible" as SistemaDisponible

package abrirAsignaturas as "abrirAsignaturas()" {
    rectangle #629EF9 ListarAsignaturasView
    rectangle #b5bd68 AsignaturaController
    rectangle #F2AC4E AsignaturaRepository
    rectangle #F2AC4E Asignatura
    rectangle #F2AC4E Grado
}

rectangle #CDEBA5 ":Sistema Disponible" as SistemaDisponibleSalida
rectangle #CDEBA5 ":Collaboration CrearAsignatura" as CrearAsignatura
rectangle #CDEBA5 ":Collaboration EditarAsignatura" as EditarAsignatura
rectangle #CDEBA5 ":Collaboration EliminarAsignatura" as EliminarAsignatura
rectangle #CDEBA5 ":Collaboration ImportarAsignaturas" as ImportarAsignaturas

SistemaDisponible -r-> ListarAsignaturasView: abrirAsignaturas()

ListarAsignaturasView -d-> AsignaturaController: listarAsignaturas(pagina) : PagedResult<Asignatura>

AsignaturaController --> AsignaturaRepository: obtenerPaginadas(pagina) : PagedResult<Asignatura>

AsignaturaRepository -- Asignatura
Asignatura -- Grado

ListarAsignaturasView --> AsignaturaController: filtrarAsignaturas(criterio, pagina) : PagedResult<Asignatura>

AsignaturaController --> AsignaturaRepository: buscarPaginadas(criterio, pagina) : PagedResult<Asignatura>

ListarAsignaturasView ..> SistemaDisponibleSalida: completarGestion()
ListarAsignaturasView ..> CrearAsignatura: crearAsignatura()
ListarAsignaturasView ..> EditarAsignatura: editarAsignatura()
ListarAsignaturasView ..> EliminarAsignatura: eliminarAsignatura()
ListarAsignaturasView ..> ImportarAsignaturas: importarAsignaturas()

@enduml
