@startuml descargarCalendarioExamenes

skinparam linetype polyline

state descargarCalendarioExamenes as "descargarCalendarioExamenes()" {

state " " as SeleccionandoFormato
state " " as GenerandoArchivo

[*] -[#green]-> SeleccionandoFormato
note on link
<b>Administrador</b> solicita descargar calendario
end note

SeleccionandoFormato -[#green]-> GenerandoArchivo
note on link
<b>Sistema</b> presenta opciones de descarga
• Permite seleccionar formato (PDF/Excel)
• Permite seleccionar período a exportar
• Permite seleccionar información a incluir
• Permite solicitar generar archivo
• Permite solicitar cancelar descarga
end note

GenerandoArchivo -[#green]-> [*]
note on link
<b>Administrador</b> introduce preferencias y solicita descargar
<b>Sistema</b> visualiza y genera el archivo del calendario
<b>Sistema</b> visualiza y prepara archivo para descarga
<b>Sistema</b> presenta enlace de descarga
<b>Administrador</b> solicita descargar archivo
end note

GenerandoArchivo -[#red]-> [*]
note on link
<b>Administrador</b> solicita cancelar descarga
<b>Sistema</b> visualiza y descarta la generación del archivo
end note
}

descargarCalendarioExamenes -[#green]-> CALENDARIO_ABIERTO
note on link
consultarCalendario()
end note

descargarCalendarioExamenes -[#red]-> CALENDARIO_ABIERTO
note on link
cancelar descarga
end note

@enduml