@startuml abrirProgramas-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":Sistema Disponible" as SistemaDisponible
package abrirProgramas as "abrirProgramas()" {
    rectangle #629EF9 AbrirProgramasView
    rectangle #b5bd68 ProgramasController
    rectangle #F2AC4E ProgramaRepository
    rectangle #F2AC4E Programa
}

rectangle #CDEBA5 ":Sistema Disponible" as SistemaDisponibleSalida
rectangle #CDEBA5 ":Collaboration CrearPrograma" as CrearPrograma
rectangle #CDEBA5 ":Collaboration EditarPrograma" as EditarPrograma
rectangle #CDEBA5 ":Collaboration EliminarPrograma" as EliminarPrograma

SistemaDisponible -r-> AbrirProgramasView: abrirProgramas()

AbrirProgramasView -d-> ProgramasController: listarProgramas() : List<Programa>

ProgramasController --> ProgramaRepository: obtenerTodos() : List<Programa>

ProgramaRepository -- Programa

AbrirProgramasView --> ProgramasController: filtrarProgramas(criterio) : List<Programa>

ProgramasController --> ProgramaRepository: buscarPorCriterio(criterio) : List<Programa>

AbrirProgramasView ..> SistemaDisponibleSalida: completarGestion()
AbrirProgramasView ..> CrearPrograma: crearPrograma()
AbrirProgramasView ..> EditarPrograma: editarPrograma()
AbrirProgramasView ..> EliminarPrograma: eliminarPrograma()

@enduml