@startuml editarGrado-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":GRADOS_ABIERTO" as GradosAbierto
rectangle #CDEBA5 ":GRADO_ABIERTO" as GradoAbierto
rectangle #CDEBA5 ":Collaboration CrearGrado" as CrearGrado
rectangle #CDEBA5 ":Collaboration AbrirGrados" as AbrirGrados
rectangle #CDEBA5 ":Collaboration AsignarExamenes" as AsignarExamenes

package editarGrado as "editarGrado()" {
    rectangle #629EF9 EditarGradoView
    rectangle #b5bd68 GradoController
    rectangle #F2AC4E GradoRepository
    rectangle #F2AC4E Grado
}

GradosAbierto --> EditarGradoView: editarGrado(gradoId)
GradoAbierto --> EditarGradoView: editarGrado(gradoId)
CrearGrado --> EditarGradoView: editarGrado(gradoNuevo)

EditarGradoView -d-> GradoController: cargarGradoParaEdición(gradoId) : Grado

GradoController --> GradoRepository: obtenerPorId(gradoId) : Grado

EditarGradoView --> GradoController: modificarCampos(gradoId, cambios) : boolean

GradoController --> GradoRepository: actualizar(grado) : boolean

GradoRepository -- Grado

EditarGradoView ..> AbrirGrados: <<include>> abrirGrados()
EditarGradoView ..> AsignarExamenes: <<include>> asignarExamenes()

@enduml