@startuml
title Consultar Detalle Alumno
skinparam linetype polyline

state ALUMNOS_ABIERTO_INICIAL as "ALUMNOS_ABIERTO"
state ALUMNOS_ABIERTO_FINAL as "ALUMNOS_ABIERTO"
state ALUMNO_ABIERTO_COMP     as "ALUMNO_ABIERTO"

[*] -[#green]-> ALUMNOS_ABIERTO_INICIAL

ALUMNOS_ABIERTO_INICIAL -[#green]-> ALUMNO_ABIERTO_COMP : consultarDetalleAlumno()
note on link
<b>Profesor</b> se encuentra en ALUMNOS_ABIERTO
y <b>solicita</b> consultar el detalle de un alumno específico.

<b>Sistema muestra</b> la información académica,
<b>presentando</b> ALUMNO_ABIERTO.
end note

state ALUMNO_ABIERTO_COMP as "ALUMNO_ABIERTO" {

    state VisualizacionFicha

    [*] -[#green]-> VisualizacionFicha
    note on link
    <b>Sistema muestra</b> la ficha completa del alumno:
    • Datos personales y Foto
    • Resumen de asistencias y faltas
    end note

    VisualizacionFicha -[#green]-> [*]
    note on link
    <b>Profesor solicita</b> realizar una acción.
    end note

}

ALUMNO_ABIERTO_COMP -[#red]-> ALUMNOS_ABIERTO_FINAL : cerrarDetalleAlumno()
note on link
<b>Sistema muestra</b> nuevamente el listado en ALUMNOS_ABIERTO.
end note

@enduml
