@startuml iniciarSesion-analisis
skinparam backgroundColor white
skinparam shadowing false
skinparam DefaultFontColor black
skinparam DefaultFontSize 12
skinparam linetype polyline

rectangle #CDEBA5 "SESION_CERRADA" as SesionCerrada
rectangle #CDEBA5 ":Collaboration PANEL_PRINCIPAL_ABIERTO" as PanelPrincipalAbierto

package "iniciarSesion()" as iniciarSesion {
    rectangle "LoginView" as LoginView #629EF9
    rectangle "IniciarSesionController" as IniciarSesionController #b5bd68
    rectangle "UsuarioRepository" as UsuarioRepository #F2AC4E
    rectangle "Usuario" as Usuario #F2AC4E
    rectangle "Sesion" as Sesion #F2AC4E
}

SesionCerrada -r-> LoginView: iniciarSesion()

LoginView -d-> IniciarSesionController: autenticar(usuario, contraseña) : Sesion

IniciarSesionController -d-> UsuarioRepository: validarCredenciales(usuario, contraseña) : Usuario
UsuarioRepository -- Usuario

IniciarSesionController -r-> Sesion: <<create>> crearSesion(usuario) : Sesion
Sesion -- Usuario

LoginView ..> PanelPrincipalAbierto: <<finalizar>> abrirPanelPrincipal()

@enduml
