@startuml eliminarGrado-analisis
skinparam linetype polyline

actor Docente
package eliminarGrado as "eliminarGrado()" {
    rectangle #629EF9 VistaEliminacionGrado
    rectangle #b5bd68 ControladorGrados
    rectangle #F2AC4E Grado
    rectangle #F2AC4E Alumno
}

Docente -r-> VistaEliminacionGrado: solicitarEliminar()
VistaEliminacionGrado --> Grado: getDatos()
VistaEliminacionGrado --> Alumno: getAlumnosAfectados()
Docente --> VistaEliminacionGrado: confirmarEliminar()
VistaEliminacionGrado -d-> ControladorGrados: eliminarGrado()
ControladorGrados --> Grado: delete()

@enduml