@startuml crearEntregable-diseño
skinparam style strictuml
skinparam backgroundColor white
skinparam shadowing false

actor Investigador
participant "Cloudflare\n(React)" as View
participant "Render\n(NestJS)" as Controller
participant "EntregableRepository\n(TypeORM)" as Repo
participant "Entregable" as Entregable

Investigador -> View: crearEntregable(proyectoId, Entregable)
activate View

View -> Controller: crearEntregable(proyectoId, Entregable)
activate Controller

Controller -> Entregable: <<create>>
activate Entregable

Entregable --> Controller: entregable
deactivate Entregable

Controller -> Repo: guardar(entregable)
activate Repo

Repo --> Controller: entregable
deactivate Repo

Controller --> View: entregable
deactivate Controller

View --> Investigador: mostrarDetalle(entregable)
deactivate View
@enduml
