@startuml solicitarEliminacionPerfil

skinparam linetype polyline

state in1 as "OPCIONES_PERFIL_ABIERTO"
in1 -[#green]-> solicitarEliminacionPerfil
note on link
solicitarEliminacionPerfil()
end note


state solicitarEliminacionPerfil as "solicitarEliminacionPerfil()" {

    state " " as SeleccionandoPerfil
    state " " as ConfirmandoSolicitud
    state " " as SolicitudEnviada

    [*] -[#green]-> SeleccionandoPerfil
    note on link
    <b>Coordinador</b> solicita la eliminacion de su perfil
    end note

    SeleccionandoPerfil -[#green]-> ConfirmandoSolicitud
    note on link
    <b>Sistema</b> presenta confirmación de solicitud de eliminación
    • Confirmar o cancelar
    end note

    ConfirmandoSolicitud -[#green]-> SolicitudEnviada
    note on link
    <b>Coordinador</b> solicita confirmar eliminación
    <b>Sistema</b> permite confirmar la solicitud de eliminación
    end note

    
    SolicitudEnviada -[#green]-> [*]
   
}


solicitarEliminacionPerfil -[#green]-> SESION_CERRADA
note on link
Solicitud enviada — sesión cerrada
end note

solicitarEliminacionPerfil -[#red]-> OPCIONES_PERFIL_ABIERTO
note on link
Solicitud cancelada
end note

@enduml
