@startuml abrirOpcionesPerfil

skinparam linetype polyline

state in1 as "INVESTIGADOR_ABIERTO"
in1 -[#blue]-> abrirOpcionesPerfil
note on link
abrirOpcionesPerfil(ID)
end note


state in2 as "PANEL_PRINCIPAL_ABIERTO"
in2 -[#green]-> abrirOpcionesPerfil
note on link
abrirOpcionesPerfil()
end note


state in3 as "SOLICITUDES_ELIMINACION_PERFIL_ABIERTAS"
in3 -[#Black]-> abrirOpcionesPerfil
note on link
abrirOpcionesPerfil()
end note



state abrirOpcionesPerfil as "abrirOpcionesPerfil()" {

    state " " as MostrandoLista
    state " " as FiltrandoLista

    [*] -[#green]-> MostrandoLista 
    note on link
    <b>Coordinador</b> solicita abrir opciones perfil
    end note    
    
    MostrandoLista -[#green]-> FiltrandoLista
    note on link
    <b>Sistema</b> presenta las opciones disponibles en perfil
    • ID, nombre, campo de cada investigador
    • Permite solicitar editar perfil
    • Permite solicitar resolver solicitud eliminacion
    • Permite solicitar volver al panel principal
    • Permite solicitar volver al investigador
    end note
    
    FiltrandoLista -[#green]-> [*]
    note on link
    <b>Coordinador</b> solicita una de las opciones
    end note
}

abrirOpcionesPerfil -[#green]-> OPCIONES_PERFIL_ABIERTO
note on link
editarPerfil()
end note


abrirOpcionesPerfil -[#green]-> SESION_CERRADA
note on link
solicitarEliminacionPerfil()
end note



abrirOpcionesPerfil -[#green]-> PANEL_PRINCIPAL_ABIERTO
note on link
abrirPanelPrincipal()
end note

abrirOpcionesPerfil -[#blue]-> INVESTIGADOR_ABIERTO
note on link
abrirInvestigador(ID)
end note


abrirOpcionesPerfil -[#Black]-> SOLICITUDES_ELIMINACION_PERFIL_ABIERTAS
note on link
abrirSolicitudesEliminacionPerfil()
end note





@enduml