@startuml exportarPreguntas-analisis
skinparam linetype polyline

note "<<abstracto>>\nInvocado desde CU-04: exportarConfiguracionGlobal" as N1
package exportarPreguntas as "exportarPreguntas()" {
    rectangle #629EF9 VistaExportacionPreguntas
    rectangle #b5bd68 ControladorExportacion
    rectangle #F2AC4E Pregunta
    rectangle #F2AC4E Respuesta
}

VistaExportacionPreguntas -d-> ControladorExportacion: recopilarPreguntas()
ControladorExportacion --> Pregunta: obtenerPreguntas()
ControladorExportacion --> Respuesta: obtenerRespuestas(pregunta)
ControladorExportacion --> VistaExportacionPreguntas: ficheroJSON

@enduml
