@startuml eliminarPublicacion-analisis
skinparam backgroundColor white
skinparam shadowing false
skinparam DefaultFontColor black
skinparam DefaultFontSize 12
skinparam linetype polyline

rectangle #CDEBA5 "MI_PUBLICACION_ABIERTA" as MiPublicacionAbierta
rectangle #CDEBA5 "MIS_PUBLICACIONES_ABIERTAS" as MisPublicacionesAbiertas

package "eliminarPublicacion()" as eliminarPublicacion {
    rectangle "EliminarPublicacionView" as EliminarPublicacionView #629EF9
    rectangle "PublicacionController" as PublicacionController #b5bd68
    rectangle "PublicacionRepository" as PublicacionRepository #F2AC4E
}

MiPublicacionAbierta -r-> EliminarPublicacionView: eliminarPublicacion()

EliminarPublicacionView -d-> PublicacionController: solicitarConfirmacion()

EliminarPublicacionView -d-> PublicacionController: confirmarEliminacion(publicacionId)
PublicacionController -d-> PublicacionRepository: eliminar(publicacionId)

EliminarPublicacionView ..> MisPublicacionesAbiertas: <<finalizar>>
EliminarPublicacionView ..> MiPublicacionAbierta: <<cancelar>>

@enduml
