@startuml abrirEntregables-analisis
skinparam backgroundColor white
skinparam shadowing false
skinparam DefaultFontColor black
skinparam DefaultFontSize 12
skinparam linetype polyline

rectangle #CDEBA5 "PROYECTO_ABIERTO" as ProyectoAbierto
rectangle #CDEBA5 "ENTREGABLES_ABIERTOS" as EntregablesAbiertos

package "abrirEntregables()" as abrirEntregables {
    rectangle "ListarEntregablesView" as ListarEntregablesView #629EF9
    rectangle "EntregableController" as EntregableController #b5bd68
    rectangle "EntregableRepository" as EntregableRepository #F2AC4E
    rectangle "Entregable" as Entregable #F2AC4E
}

rectangle #CDEBA5 ":Collaboration AbrirEntregable" as AbrirEntregable
rectangle #CDEBA5 ":Collaboration CrearEntregable" as CrearEntregable
rectangle #CDEBA5 ":Collaboration AbrirProyecto" as AbrirProyecto

ProyectoAbierto -r-> ListarEntregablesView: abrirEntregables(proyectoId)

ListarEntregablesView -d-> EntregableController: listarEntregables(proyectoId) : List<Entregable>
EntregableController -d-> EntregableRepository: obtenerPorProyecto(proyectoId) : List<Entregable>
EntregableRepository -- Entregable

ListarEntregablesView ..> AbrirEntregable: abrirEntregable(entregableId)
ListarEntregablesView ..> CrearEntregable: crearEntregable()
ListarEntregablesView ..> AbrirProyecto: abrirProyecto()

ListarEntregablesView ..> EntregablesAbiertos: <<finalizar>>

@enduml
