@startuml crearRecompensa
skinparam style strictuml
skinparam backgroundColor white
skinparam shadowing false

actor Coordinador
participant "Cloudflare\n(React)" as View
participant "Render\n(NestJS)" as Controller
participant "Recompensa\n(Entidad)" as Entidad
participant "RecompensaRepository\n(TypeORM)" as Repository

Coordinador -> View: crearRecompensa(Recompensa)
activate View

View -> Controller: crearRecompensa(Recompensa)
activate Controller

Controller -> Entidad: <<create>>
activate Entidad

Entidad --> Controller: nuevaRecompensa
deactivate Entidad

Controller -> Repository: guardarRecompensa(nuevaRecompensa)
activate Repository

Repository --> Controller: Recompensa
deactivate Repository

Controller --> View: Recompensa
deactivate Controller

View --> Coordinador: mostrarDetalle(Recompensa)
deactivate View
@enduml