@startuml eliminarDocente-analisis
skinparam linetype polyline

actor AdministradorInstitucional
package eliminarDocente as "eliminarDocente()" {
    rectangle #629EF9 VistaEliminacionDocente
    rectangle #b5bd68 ControladorDocentes
    rectangle #F2AC4E Docente
}

AdministradorInstitucional -r-> VistaEliminacionDocente: solicitarEliminar()
VistaEliminacionDocente --> Docente: getDatos()
AdministradorInstitucional --> VistaEliminacionDocente: confirmarEliminar()
VistaEliminacionDocente -d-> ControladorDocentes: eliminarDocente()
ControladorDocentes --> Docente: delete()

@enduml
