@startuml SDiagramaClases

title "Diagrama de Clases Unificado: Gestión de Proyectos + Red de Investigadores"

class Proyecto <<Principal>> #FFAAAA {
}

class Convocatoria {
}

class Propuesta {
}

class InvestigadorDocente {
}

class Coordinador {
}

class Colaborador {
}

class CargaTrabajo {
}

class Entregables {
}

class Recompensa {
}

class PerfilInvestigador {
}

class Publicacion {
    
}


Convocatoria --> Propuesta : genera
Propuesta --> Proyecto : genera


Proyecto o-- InvestigadorDocente : "está formado por"
Proyecto *-- Entregables : tiene
Proyecto *-- CargaTrabajo : genera
Proyecto *-- Recompensa : genera


Coordinador --> Proyecto : coordina
Coordinador --> Convocatoria : busca
Coordinador --> InvestigadorDocente : recluta


Colaborador --> Proyecto : participa


InvestigadorDocente --> CargaTrabajo : tiene
InvestigadorDocente *-- PerfilInvestigador : tiene
InvestigadorDocente --> InvestigadorDocente : interactúa con
InvestigadorDocente --> Entregables : genera
InvestigadorDocente --> Publicacion: publica
InvestigadorDocente --> Publicacion: responde


Recompensa --> InvestigadorDocente : beneficia

@enduml