@startuml crearProfesor-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":Profesores Abierto" as ProfesoresAbierto
rectangle #CDEBA5 ":Collaboration EditarProfesor" as EditarProfesor

package crearProfesor as "crearProfesor()" {
    rectangle #629EF9 CrearProfesorView
    rectangle #b5bd68 ProfesorController
    rectangle #F2AC4E ProfesorRepository
    rectangle #F2AC4E Profesor
}

ProfesoresAbierto -r-> CrearProfesorView: crearProfesor()

CrearProfesorView -d-> ProfesorController: validarDatosMínimos(codigo, nombres, apellidos) : boolean

ProfesorController --> ProfesorRepository: verificarUnicidad(codigo) : boolean

CrearProfesorView --> ProfesorController: crearProfesor(codigo, nombres, apellidos) : Profesor

ProfesorController --> ProfesorRepository: crear(codigo, nombres, apellidos) : Profesor

ProfesorRepository -- Profesor

CrearProfesorView ..> EditarProfesor: <<include>> editarProfesor(profesorNuevo)

@enduml