@startuml diagrama-contexto-visitante
left to right direction
skinparam linetype polyline

state "SESION_CERRADA" as NoAuth
state "UNIVERSIDAD_DISPONIBLE" as Universidad
state "RECORRIDOS_ABIERTOS" as ListRecorridos
state "RECORRIDO_ABIERTO" as Recorrido
state "ESPACIO_ABIERTO" as Espacio


[*] --> NoAuth

' --- Inicio y salida ---
NoAuth --> Universidad : iniciarVisita()
Universidad --> NoAuth : salir()

' --- Recorridos disponibles ---
Universidad --> ListRecorridos : listarRecorridos()
ListRecorridos --> Universidad : abrirUniversidad()

' --- Seleccionar recorrido ---
ListRecorridos --> Recorrido : seleccionarRecorrido()

' --- Acciones sobre espacio ---
Recorrido --> Espacio : buscarEspacio()
Recorrido --> Espacio : verDetalles()
Recorrido --> Espacio : verEspaciosCercanos()
Recorrido --> Espacio : verEspaciosPlanta()
Recorrido --> Espacio : verEspacio()
Recorrido --> Espacio : cambiarDeEspacio()


Espacio --> Espacio : verDetalles()
Espacio --> Espacio : verEspaciosCercanos()
Espacio --> Espacio : verEspaciosPlanta()
Espacio --> Espacio : cambiarDeEspacio()
Espacio --> Espacio : verEspacio()
Espacio --> ListRecorridos :listarRecorridos()

@enduml
