@startuml
skinparam nodesep 60
skinparam ranksep 60
skinparam linetype polyline
skinparam NoteBackgroundColor lightyellow
skinparam NoteBorderColor gray
skinparam StateBackgroundColor #F5F5F5
skinparam StateBorderColor gray

state "consultarUsuario()" as consultarUsuario {
   
    ' Estados anónimos vacíos para simular los pasos
    state " " as Paso1
    state " " as Paso2
   
    [*] -[#green]-> Paso1
    note on link
      <b>Administrador</b> solicita mostrar usuario
    end note
   
    Paso1 -[#green]-> Paso2
    note on link
      <b>Sistema</b> permite mostrar los datos del usuario:
      • Nombres Completos y DNI / Pasaporte
      • Correo Electrónico
      • Rol en el Sistema y Estado (Activo/Inactivo)
    end note
   
    Paso2 -[#green]-> [*]
    note on link
      <b>Administrador</b> revisa la información del usuario
      <b>Sistema</b> permite mantener los datos en pantalla
      • Permite solicitar editar usuario
      • Permite solicitar cerrar usuario
    end note
}


state "USUARIO_ABIERTO" as USUARIO_ABIERTO
state "USUARIOS_ABIERTO" as USUARIOS_ABIERTO

consultarUsuario -[#green]---> USUARIO_ABIERTO
note right on link
  editarUsuario()
end note

consultarUsuario -[#blue]---> USUARIOS_ABIERTO
note right on link
  abrirUsuarios()
end note
@enduml