@startuml crearProyecto
skinparam style strictuml
skinparam backgroundColor white
skinparam shadowing false

actor Coordinador
participant "Cloudflare\n(React)" as View
participant "Render\n(NestJS)" as Controller
participant "Proyecto\n(Entidad)" as Entidad
participant "ProyectoRepository\n(TypeORM)" as Repository

Coordinador -> View: crearProyecto(nuevoProyecto)
activate View

View -> Controller: crearProyecto(nuevoProyecto)
activate Controller

Controller -> Entidad: <<create>>
activate Entidad

Entidad --> Controller: nuevoProyecto
deactivate Entidad

Controller -> Repository: guardar(nuevoProyecto)
activate Repository

Repository --> Controller: NuevoProyecto
deactivate Repository

Controller --> View: NuevoProyecto
deactivate Controller

View --> Coordinador: mostrarDetalle(NuevoProyecto)
deactivate View
@enduml