@startuml editarExamen

skinparam linetype polyline

state editarExamen as "editarExamen()" {

state " " as EditandoDatos
state " " as GuardandoDatos

[*] -[#green]-> EditandoDatos
note on link
<b>Administrador</b> solicita editar examen
end note

EditandoDatos -[#green]-> GuardandoDatos
note on link
<b>Sistema</b> presenta datos de edición
• Permite introducir nuevo código
• Permite introducir nueva fecha y hora
• Permite introducir nueva duración
• Permite solicitar cambiar asignatura asociada
• Permite solicitar cambiar aula asignada
• Permite solicitar guardar cambios
• Permite solicitar cancelar edición
end note

GuardandoDatos -[#green]-> EditandoDatos
note on link
<b>Administrador</b> solicita modificar campos
<b>Sistema</b> permite introducir nuevos valores
end note

GuardandoDatos -[#green]-> [*]
note on link
<b>Administrador</b> solicita guardar y salir
<b>Sistema</b> visualiza y actualiza el examen en la base de datos
end note

GuardandoDatos -[#red]-> [*]
note on link
<b>Administrador</b> solicita cancelar edición
<b>Sistema</b> visualiza y descarta los cambios realizados
end note
}

editarExamen -[#green]-> EXAMENES_ABIERTO
note on link
abrirExamenes()
end note

editarExamen -[#red]-> EXAMENES_ABIERTO
note on link
cancelar edición
end note

@enduml