@startuml crearPublicacion-analisis
skinparam backgroundColor white
skinparam shadowing false
skinparam DefaultFontColor black
skinparam DefaultFontSize 12
skinparam linetype polyline

rectangle #CDEBA5 "MIS_PUBLICACIONES_ABIERTAS" as MisPublicacionesAbiertas
rectangle #CDEBA5 "MI_PUBLICACION_ABIERTA" as MiPublicacionAbierta

package "crearPublicacion()" as crearPublicacion {
    rectangle "CrearPublicacionView" as CrearPublicacionView #629EF9
    rectangle "PublicacionController" as PublicacionController #b5bd68
    rectangle "PublicacionRepository" as PublicacionRepository #F2AC4E
    rectangle "Publicacion" as Publicacion #F2AC4E
    rectangle "Sesion" as Sesion #F2AC4E
}

MisPublicacionesAbiertas -r-> CrearPublicacionView: crearPublicacion()

CrearPublicacionView -d-> PublicacionController: crear(titulo, estado, visibilidad, descripcion) : Publicacion
PublicacionController -d-> Sesion: getUsuarioActual() : Usuario
PublicacionController -r-> Publicacion: <<create>>
PublicacionController -d-> PublicacionRepository: guardar(publicacion)

CrearPublicacionView ..> MiPublicacionAbierta: <<finalizar>> abrirMiPublicacion(publicacion)
CrearPublicacionView ..> MisPublicacionesAbiertas: <<cancelar>> abrirMisPublicaciones()

@enduml
