@startuml eliminarProfesor-analisis
skinparam backgroundColor white
skinparam shadowing false
skinparam DefaultFontColor black
skinparam DefaultFontSize 12
skinparam linetype polyline

rectangle #CDEBA5 ":Profesores Abierto" as ProfesoresAbierto

package eliminarProfesor as "eliminarProfesor()" {
    rectangle #629EF9 EliminarProfesorView
    rectangle #b5bd68 ProfesorController
    rectangle #F2AC4E ProfesorRepository
    rectangle #F2AC4E Profesor
}

rectangle #F2AC4E ExamenRepository
rectangle #F2AC4E PreferenciaRepository
rectangle #CDEBA5 ":Profesores Abierto" as ProfesoresAbiertoSalida

ProfesoresAbierto -r-> EliminarProfesorView: eliminarProfesor(profesor)

EliminarProfesorView -d-> ProfesorController: verificarExamenesAsignados(profesor) : Integer

ProfesorController -d-> ExamenRepository: contarPorProfesor(profesor) : Integer

EliminarProfesorView -d-> ProfesorController: eliminar(profesor)

ProfesorController -d-> PreferenciaRepository: eliminarPorProfesor(profesor)
ProfesorController -d-> ProfesorRepository: eliminar(profesor)

EliminarProfesorView ..> ProfesoresAbiertoSalida: <<finalizar>>
EliminarProfesorView ..> ProfesoresAbiertoSalida: <<cancelar>>

@enduml
