@startuml DiagramaContextoInvestigador

title Diagrama de contexto de un investigador

left to right direction

[*] --> SESION_CERRADA
SESION_CERRADA --> PANEL_PRINCIPAL_ABIERTO: iniciarSesion()
PANEL_PRINCIPAL_ABIERTO --> SESION_CERRADA: cerrarSesion()

PANEL_PRINCIPAL_ABIERTO --> OPCIONES_PERFIL_ABIERTO: abrirOpcionesPerfil()
PANEL_PRINCIPAL_ABIERTO --> OPCIONES_CARGA_TRABAJO_ABIERTAS: abrirOpcionesCargaTrabajo()
PANEL_PRINCIPAL_ABIERTO --> PROYECTOS_ABIERTOS: abrirProyectos()
PANEL_PRINCIPAL_ABIERTO --> INVESTIGADORES_ABIERTOS: abrirInvestigadores()
PANEL_PRINCIPAL_ABIERTO --> MIS_PUBLICACIONES_ABIERTAS: abrirMisPublicaciones()
PANEL_PRINCIPAL_ABIERTO --> PUBLICACIONES_ABIERTAS: abrirPublicaciones()
PANEL_PRINCIPAL_ABIERTO --> RECOMPENSAS_ABIERTAS: abrirRecompensas()



OPCIONES_PERFIL_ABIERTO --> OPCIONES_PERFIL_ABIERTO: editarPerfil()
OPCIONES_PERFIL_ABIERTO --> SESION_CERRADA: solicitarEliminacionPerfil()
OPCIONES_PERFIL_ABIERTO --> PANEL_PRINCIPAL_ABIERTO: abrirPanelPrincipal()

OPCIONES_CARGA_TRABAJO_ABIERTAS --> OPCIONES_CARGA_TRABAJO_ABIERTAS: editarCargaTrabajo()
OPCIONES_CARGA_TRABAJO_ABIERTAS --> PANEL_PRINCIPAL_ABIERTO: abrirPanelPrincipal()

PUBLICACIONES_ABIERTAS --> PUBLICACION_ABIERTA: abrirPublicacion()
PUBLICACION_ABIERTA --> PUBLICACION_ABIERTA: responderPublicacion()
PUBLICACION_ABIERTA --> PUBLICACIONES_ABIERTAS: abrirPublicaciones()
PUBLICACIONES_ABIERTAS --> PANEL_PRINCIPAL_ABIERTO: abrirPanelPrincipal()

MIS_PUBLICACIONES_ABIERTAS --> MI_PUBLICACION_ABIERTA: abrirMiPublicacion()
MIS_PUBLICACIONES_ABIERTAS --> MI_PUBLICACION_ABIERTA: crearPublicacion()
MI_PUBLICACION_ABIERTA --> MI_PUBLICACION_ABIERTA: editarPublicacion()
MI_PUBLICACION_ABIERTA --> MIS_PUBLICACIONES_ABIERTAS: eliminarPublicacion()
MIS_PUBLICACIONES_ABIERTAS --> PANEL_PRINCIPAL_ABIERTO: abrirPanelPrincipal()
MI_PUBLICACION_ABIERTA --> MIS_PUBLICACIONES_ABIERTAS: abrirMisPublicaciones()

PROYECTOS_ABIERTOS --> PROYECTO_ABIERTO: abrirProyecto()
PROYECTOS_ABIERTOS --> PANEL_PRINCIPAL_ABIERTO: abrirPanelPrincipal()

RECOMPENSAS_ABIERTAS --> RECOMPENSA_ABIERTA: abrirRecompensa()
RECOMPENSA_ABIERTA --> RECOMPENSAS_ABIERTAS: abrirRecompensas()
RECOMPENSAS_ABIERTAS --> PANEL_PRINCIPAL_ABIERTO: abrirPanelPrincipal()


PROYECTO_ABIERTO --> ENTREGABLES_ABIERTOS: abrirEntregables()
ENTREGABLES_ABIERTOS --> ENTREGABLE_ABIERTO: crearEntregable()
PROYECTO_ABIERTO --> INVESTIGADORES_ABIERTOS: abrirInvestigadores()
PROYECTO_ABIERTO --> PROYECTOS_ABIERTOS: abrirProyectos()

ENTREGABLE_ABIERTO --> ENTREGABLE_ABIERTO: editarEntregable()
ENTREGABLES_ABIERTOS--> ENTREGABLE_ABIERTO: abrirEntregable()
ENTREGABLE_ABIERTO --> ENTREGABLES_ABIERTOS: eliminarEntregable()
ENTREGABLES_ABIERTOS --> PROYECTO_ABIERTO: abrirProyecto()
ENTREGABLE_ABIERTO --> ENTREGABLES_ABIERTOS: abrirEntregables()

INVESTIGADORES_ABIERTOS --> INVESTIGADOR_ABIERTO: abrirInvestigador()
INVESTIGADORES_ABIERTOS --> PANEL_PRINCIPAL_ABIERTO: abrirPanelPrincipal()
INVESTIGADOR_ABIERTO --> INVESTIGADORES_ABIERTOS: abrirInvestigadores()
INVESTIGADOR_ABIERTO --> PROYECTOS_ABIERTOS: abrirProyectos()

@enduml