@startuml eliminarPregunta-analisis
skinparam linetype polyline

actor Docente
package eliminarPregunta as "eliminarPregunta()" {
    rectangle #629EF9 VistaEliminacionPregunta
    rectangle #b5bd68 ControladorPreguntas
    rectangle #F2AC4E Pregunta
}

Docente -r-> VistaEliminacionPregunta: solicitarEliminacion(id)
VistaEliminacionPregunta -d-> ControladorPreguntas: obtenerDatosPregunta(id)
ControladorPreguntas --> Pregunta: getDetalles()
VistaEliminacionPregunta --> VistaEliminacionPregunta: mostrarAdvertencia()

Docente --> VistaEliminacionPregunta: confirmarEliminacion()
VistaEliminacionPregunta --> ControladorPreguntas: eliminarDefinitivamente(id)
ControladorPreguntas --> Pregunta: delete()

@enduml