@startuml eliminarInvestigador-analisis
skinparam backgroundColor white
skinparam shadowing false
skinparam DefaultFontColor black
skinparam DefaultFontSize 12
skinparam linetype polyline

rectangle #CDEBA5 "PROYECTO_ABIERTO" as ProyectoAbierto

package "eliminarInvestigador()" as eliminarInvestigador {
    rectangle "EliminarInvestigadorView" as EliminarInvestigadorView #629EF9
    rectangle "ProyectoController" as ProyectoController #b5bd68
    rectangle "ProyectoRepository" as ProyectoRepository #F2AC4E
}

ProyectoAbierto -r-> EliminarInvestigadorView: eliminarInvestigador(investigadorId)

EliminarInvestigadorView -d-> ProyectoController: solicitarConfirmacionEliminacion()

EliminarInvestigadorView -d-> ProyectoController: confirmarDesvinculacion(proyectoId, investigadorId)
ProyectoController -d-> ProyectoRepository: eliminarAsociacion(proyectoId, investigadorId)

EliminarInvestigadorView ..> ProyectoAbierto: <<finalizar>>
EliminarInvestigadorView ..> ProyectoAbierto: <<cancelar>>

@enduml
