@startuml crearGrupo-analisis
skinparam linetype polyline

actor Usuario
package crearGrupo as "crearGrupo()" {
    rectangle #629EF9 CrearGrupoView
    rectangle #b5bd68 GruposController
    rectangle #F2AC4E GrupoRepository
    rectangle #F2AC4E Grupo
    rectangle #F2AC4E MiembroGrupo
}
rectangle #CDEBA5 ":Sistema Disponible" as SistemaDisponible

SistemaDisponible -r-> CrearGrupoView: 1: crearGrupo()

CrearGrupoView -d-> GruposController: 2: registrarGrupo(datos, creador)

GruposController --> GrupoRepository: 3: crearGrupoConAdministrador(datos, creador)

GrupoRepository -- Grupo
GrupoRepository -- MiembroGrupo

CrearGrupoView -r-> SistemaDisponible: 4: sistemaDisponible(usuario)

@enduml
