@startuml secuencia-diseño
skinparam shadowing false

actor Administrador
participant "ExamenCreateView\n(React)" as UI <<Component>>
participant "useExamenForm\n(Hook)" as Hook <<Hook>>
participant "ExamenesService\n(Axios)" as FService <<Service>>
participant "ExamenesController\n(NestJS)" as Controller <<Controller>>
participant "ExamenesService\n(NestJS)" as BService <<Service>>
database "PostgreSQL" as DB

Administrador -> UI : Rellena formulario de nuevo examen
Administrador -> UI : Click en "Guardar"
UI -> Hook : submit(data)
Hook -> FService : createExamen(data)
FService -> Controller : POST /examenes (JSON Body)
Controller -> BService : create(dto)
BService -> BService : Validar aulas disponibles
BService -> BService : Validar código único
BService -> DB : INSERT INTO "Examen" (...)
DB --> BService : Examen Creado (with UUID)
BService --> Controller : Examen Entity
Controller --> FService : JSON Response (201 Created)
FService --> Hook : Examen Object
Hook --> UI : Redirigir a listado / Mostrar éxito
UI --> Administrador : Muestra confirmación de creación
@enduml
