@startuml
skinparam style strictuml
title Diagrama de Estados: Asistencia

[*] --> Programada : crearSesionClase()

Programada --> Programada : editarSesionClase()
Programada --> AsistenciaPendiente : iniciarSesionClase()
Programada --> Cerrada : cerrarSesionClase()


AsistenciaPendiente --> AsistenciaRegistrada : registrarTomaAsistencia()
AsistenciaRegistrada --> AsistenciaRegistrada : registrarTomaAsistencia()


AsistenciaRegistrada --> Cerrada : cerrarSesionClase()
Cerrada --> Cerrada : exportarHistorialAsistencias()

Cerrada --> [*]
@enduml