@startuml abrirOpcionesPerfil-analisis
skinparam backgroundColor white
skinparam shadowing false
skinparam DefaultFontColor black
skinparam DefaultFontSize 12
skinparam linetype polyline

rectangle #CDEBA5 "PANEL_PRINCIPAL_ABIERTO" as PanelPrincipalAbierto
rectangle #CDEBA5 "OPCIONES_PERFIL_ABIERTO" as OpcionesPerfilAbierto

package "abrirOpcionesPerfil()" as abrirOpcionesPerfil {
    rectangle "OpcionesPerfilView" as OpcionesPerfilView #629EF9
    rectangle "OpcionesPerfilController" as OpcionesPerfilController #b5bd68
    rectangle "UsuarioRepository" as UsuarioRepository #F2AC4E
    rectangle "Usuario" as Usuario #F2AC4E
    rectangle "Sesion" as Sesion #F2AC4E
}

rectangle #CDEBA5 ":Collaboration EditarPerfil" as EditarPerfil
rectangle #CDEBA5 ":Collaboration SolicitarEliminacionPerfil" as SolicitarEliminacionPerfil
rectangle #CDEBA5 ":Collaboration AbrirPanelPrincipal" as AbrirPanelPrincipal

PanelPrincipalAbierto -r-> OpcionesPerfilView: abrirOpcionesPerfil()

OpcionesPerfilView -d-> OpcionesPerfilController: cargarDatosPerfil()

OpcionesPerfilController -d-> Sesion: getUsuarioActual() : Usuario
OpcionesPerfilController -d-> UsuarioRepository: obtenerPorId(usuarioId) : Usuario

OpcionesPerfilView ..> EditarPerfil: editarPerfil()
OpcionesPerfilView ..> SolicitarEliminacionPerfil: solicitarEliminacionPerfil()
OpcionesPerfilView ..> AbrirPanelPrincipal: abrirPanelPrincipal()

OpcionesPerfilView ..> OpcionesPerfilAbierto: <<finalizar>>

@enduml
