@startsalt abrirPanelPrincipal-wireframe
{
    ====
    GIPF - Panel principal
    ====
    {^" Panel principal "
        Bienvenido, Coordinador

        .
        Accesos principales:
        {
            [Proyectos] | [Investigadores] | [Convocatorias] | [Recompensas]
        }
        .
        Publicaciones:
        {
            [Mis publicaciones] | [Publicaciones]
        }
        .
        Ajustes:
        {
            [Opciones de perfil] | [Carga de trabajo de investigadores] | [Cerrar sesión]
        }
    }
}
@endsalt
