@startuml crearUsuario-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":Usuarios Abierto" as UsuariosAbierto

package crearUsuario as "crearUsuario()" {
    rectangle #629EF9 CrearUsuarioView
    rectangle #b5bd68 UsuarioController
    rectangle #F2AC4E UsuarioRepository
    rectangle #F2AC4E Usuario
}

UsuariosAbierto -r-> CrearUsuarioView: crearUsuario()
CrearUsuarioView -d-> UsuarioController: crearUsuario(nombres, apellidos, dni, correo, rol)
UsuarioController --> UsuarioRepository: create(nombres, apellidos, dni, correo, rol)
UsuarioRepository -- Usuario
@enduml