@startuml exportarGrados-analisis
skinparam linetype polyline

note "<<abstracto>>\nInvocado desde CU-04: exportarConfiguracionGlobal" as N1
package exportarGrados as "exportarGrados()" {
    rectangle #629EF9 VistaExportacionGrados
    rectangle #b5bd68 ControladorExportacionGrados
    rectangle #F2AC4E Grado
}

VistaExportacionGrados -d-> ControladorExportacionGrados: procesarExportacion()
ControladorExportacionGrados --> Grado: obtenerDatosGrados()
ControladorExportacionGrados --> VistaExportacionGrados: ficheroJSON

@enduml
