@startsalt crearProyecto-wireframe
{
    ====
    <b>GIPF - CREAR PROYECTO</b>
    ====
    {
        <b>Datos mínimos del proyecto</b>
        --
        {
            {<b>Título *</b> | [                                      ]}
            {<b>Convocatoria de origen</b> | ^Seleccionar convocatoria^}
            {<b>Fecha de inicio prevista</b> | [            ]}
            {<b>Fecha de fin prevista</b> | [            ]}
            {<b>Descripción inicial</b> | [                                      ]}
        }
        --
        <i>El sistema asignará el código, el Coordinador responsable y el estado Creado.</i>
        <i>Después de crearlo se abrirá para continuar su definición.</i>
        --
        {[Crear proyecto] | [Cancelar]}
    }
}
@endsalt
