@startuml cerrarSesion-analisis
skinparam linetype polyline

actor Usuario
package cerrarSesion as "cerrarSesion()" {
    rectangle #629EF9 VistaSesion
    rectangle #b5bd68 ControladorCierreSesion
    rectangle #F2AC4E SesionUsuario
}

Usuario -r-> VistaSesion: solicitarCierre()
VistaSesion --> Usuario: pedirConfirmacion()
Usuario --> VistaSesion: confirmarCierre()
VistaSesion -d-> ControladorCierreSesion: cerrarSesion()
ControladorCierreSesion --> SesionUsuario: invalidar()

@enduml