@startuml crearGrupo
skinparam monochrome false
skinparam shadow false
top to bottom direction

skinparam state {
    BackgroundColor White
    BorderColor Black
    ArrowColor #009900
    StartColor Black
    EndColor Black
}


skinparam note {
    BackgroundColor #FFFFE0
    BorderColor #B0B060
    FontName Arial
}

state "GRUPOS_ABIERTO" as Inicio

state "crearGrupo()" as CrearGrupoContainer {
    
    state " " as EstadoFormulario
    state " " as EstadoDecision
    
    [*] --> EstadoFormulario
    note on link
        **Administrador** solicita crear grupo
    end note

    EstadoFormulario --> EstadoDecision
    note on link
        **Sistema** presenta solicitud de datos mínimos del grupo
        **Sistema** permite solicitar:
        * introducir nombre (obligatorio) y descripción
        * crear grupo
        * cancelar creación
    end note

    EstadoDecision -[#green]up-> EstadoFormulario
    note on link
        **Administrador** solicita modificar datos introducidos
    end note

    EstadoDecision -[#green]down-> [*]
    note on link
        **Administrador** introduce datos y solicita crear grupo
    end note

    EstadoDecision -[#red]down-> [*]
    note on link
        **Administrador** solicita cancelar creación
    end note
}

state "GRUPO_ABIERTO" as FinExito
state "GRUPOS_ABIERTO" as FinCancelacion

Inicio --> CrearGrupoContainer

CrearGrupoContainer -[#green]-> FinExito : "               "

CrearGrupoContainer -[#red]down-> FinCancelacion
note on link
    cancelar creación
end note

@enduml