@startuml asignarTareaAUsuario-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":Estado origen SdR" as EstadoOrigen
rectangle #CDEBA5 ":Estado destino SdR" as EstadoDestino

package "asignarTareaAUsuario()" {
    rectangle #629EF9 AsignarTareaAUsuarioView
    rectangle #b5bd68 AsignarTareaAUsuarioController
    rectangle #F2AC4E RepositorioDominio
    rectangle #F2AC4E EntidadDominio
}

EstadoOrigen --> AsignarTareaAUsuarioView: asignarTareaAUsuario()
AsignarTareaAUsuarioView --> AsignarTareaAUsuarioController: coordinarCasoUso()
AsignarTareaAUsuarioController --> RepositorioDominio: consultarOModificarDominio()
RepositorioDominio -- EntidadDominio
AsignarTareaAUsuarioView --> EstadoDestino: presentaResultado()

@enduml
