@startuml abrirEdificios-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":Sistema Disponible" as SistemaDisponible
package abrirEdificios as "abrirEdificios()" {
    rectangle #629EF9 ListarEdificiosView
    rectangle #b5bd68 EdificiosController
    rectangle #F2AC4E EdificioRepository
    rectangle #F2AC4E Edificio
}

rectangle #CDEBA5 ":Sistema Disponible" as SistemaDisponibleSalida
rectangle #CDEBA5 ":Collaboration CrearEdificio" as CrearEdificio
rectangle #CDEBA5 ":Collaboration EditarEdificio" as EditarEdificio
rectangle #CDEBA5 ":Collaboration EliminarEdificio" as EliminarEdificio

SistemaDisponible -r-> ListarEdificiosView: abrirEdificios()

ListarEdificiosView -d-> EdificiosController: listarEdificios() : List<Edificio>

EdificiosController --> EdificioRepository: obtenerTodos() : List<Edificio>

EdificioRepository -- Edificio

ListarEdificiosView --> EdificiosController: filtrarEdificios(criterio) : List<Edificio>

EdificiosController --> EdificioRepository: buscarPorCriterio(criterio) : List<Edificio>

ListarEdificiosView ..> SistemaDisponibleSalida: completarGestion()
ListarEdificiosView ..> CrearEdificio: crearEdificio()
ListarEdificiosView ..> EditarEdificio: editarEdificio()
ListarEdificiosView ..> EliminarEdificio: eliminarEdificio()

@enduml