@startuml solicitarEliminacionPerfil
skinparam style strictuml
skinparam backgroundColor white
skinparam shadowing false

actor Investigador
participant "Cloudflare\n(React)" as View
participant "Render\n(NestJS)" as Controller
participant "Sesion" as Sesion
participant "SolicitudEliminacion\n(Entidad)" as Entidad
participant "SolicitudEliminacionRepository\n(TypeORM)" as Repo

Investigador -> View : solicitarEliminacionPerfil()
activate View

View -> Controller : solicitarEliminacionPerfil()
activate Controller

Controller -> Sesion : getUsuarioActual()
activate Sesion
Sesion --> Controller : usuario
deactivate Sesion

Controller -> Repo : crearSolicutud(usuario, solicitudEliminacion)
activate Repo
Repo --> Controller : SolicitudEliminacion
deactivate Repo

Controller --> View : SolicitudEliminacion
deactivate Controller

View --> Investigador : mostrarDetalle(SolicitudEliminacion)
deactivate View
@enduml