@startuml eliminarRespuesta-analisis
skinparam linetype polyline

actor Docente
package eliminarRespuesta as "eliminarRespuesta()" {
    rectangle #629EF9 VistaEliminacionRespuesta
    rectangle #b5bd68 ControladorEliminacionRespuestas
    rectangle #F2AC4E Respuesta
}

Docente -r-> VistaEliminacionRespuesta: solicitarEliminar()
VistaEliminacionRespuesta --> Respuesta: getDatos()
Docente --> VistaEliminacionRespuesta: confirmarEliminar()
VistaEliminacionRespuesta -d-> ControladorEliminacionRespuestas: eliminarRespuesta()
ControladorEliminacionRespuestas --> Respuesta: delete()

@enduml