@startuml editarProfesor-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":Profesores Abierto" as ProfesoresAbierto
rectangle #CDEBA5 ":Profesor Abierto" as ProfesorAbierto
rectangle #CDEBA5 ":Collaboration CrearProfesor" as CrearProfesor
rectangle #CDEBA5 ":Collaboration AbrirProfesores" as AbrirProfesores

package editarProfesor as "editarProfesor()" {
    rectangle #629EF9 EditarProfesorView
    rectangle #b5bd68 ProfesorController
    rectangle #F2AC4E ProfesorRepository
    rectangle #F2AC4E Profesor
}

ProfesoresAbierto --> EditarProfesorView: editarProfesor(profesorId)
ProfesorAbierto --> EditarProfesorView: editarProfesor(profesorId)
CrearProfesor --> EditarProfesorView: editarProfesor(profesorNuevo)

EditarProfesorView -d-> ProfesorController: cargarProfesorParaEdición(profesorId) : Profesor

ProfesorController --> ProfesorRepository: obtenerPorId(profesorId) : Profesor

EditarProfesorView --> ProfesorController: modificarCampos(profesorId, cambios) : boolean

ProfesorController --> ProfesorRepository: actualizar(profesor) : boolean

ProfesorRepository -- Profesor

EditarProfesorView ..> AbrirProfesores: <<include>> abrirProfesores()

@enduml