@startuml abrirEntregable-diseño
skinparam style strictuml
skinparam backgroundColor white
skinparam shadowing false
skinparam DefaultFontColor black
skinparam DefaultFontSize 12
skinparam linetype polyline

actor Usuario
participant "Cloudflare\n(React)" as View
participant "Render\n(NestJS)" as Controller
participant "EntregableRepository\n(TypeORM)" as Repository

Usuario -> View : abrirEntregable(entregableId)
activate View

View -> Controller : obtenerDetalleEntregable(entregableId)
activate Controller

Controller -> Repository : obtenerPorId(entregableId)
activate Repository

Repository --> Controller : Entregable
deactivate Repository

Controller --> View : Entregable
deactivate Controller

View --> Usuario : mostrarDetalle(Entregable)
deactivate View

@enduml