@startuml abrirTareas-analisis
skinparam linetype polyline
left to right direction

actor Usuario
boundary ListarTareasView
control TareasController
entity TareaRepository
entity Tarea
entity Grupo
rectangle ":Sistema Disponible" as SistemaDisponible #C5E0B4

Usuario --> ListarTareasView : 1: abrirTareas()
ListarTareasView --> TareasController : 2: listarTareas(grupo)
TareasController --> TareaRepository : 3: obtenerTareasPorGrupo(grupo)
TareaRepository -- Tarea
TareaRepository -- Grupo
ListarTareasView --> SistemaDisponible : 4: sistemaDisponible(usuario)

@enduml