@startuml editarEdificio-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":Edificios Abierto" as EdificiosAbierto
rectangle #CDEBA5 ":Edificio Abierto" as EdificioAbierto
rectangle #CDEBA5 ":Collaboration CrearEdificio" as CrearEdificio
rectangle #CDEBA5 ":Collaboration AbrirEdificios" as AbrirEdificios

package editarEdificio as "editarEdificio()" {
    rectangle #629EF9 EditarEdificioView
    rectangle #b5bd68 EdificioController
    rectangle #F2AC4E EdificioRepository
    rectangle #F2AC4E Edificio
}

EdificiosAbierto --> EditarEdificioView: editarEdificio(edificioId)
EdificioAbierto --> EditarEdificioView: editarEdificio(edificioId)
CrearEdificio --> EditarEdificioView: editarEdificio(edificioNuevo)

EditarEdificioView -d-> EdificioController: cargarEdificioParaEdición(edificioId) : Edificio

EdificioController --> EdificioRepository: obtenerPorId(edificioId) : Edificio

EditarEdificioView --> EdificioController: modificarCampos(edificioId, cambios) : boolean

EdificioController --> EdificioRepository: actualizar(edificio) : boolean

EdificioRepository -- Edificio

EditarEdificioView ..> AbrirEdificios: <<include>> abrirEdificios()

@enduml