@startuml abrirUsuarios-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":Sistema Disponible" as SistemaDisponible

package abrirUsuarios as "abrirUsuarios()" {
    rectangle #629EF9 AbrirUsuariosView
    rectangle #b5bd68 UsuarioController
    rectangle #F2AC4E UsuarioRepository
    rectangle #F2AC4E Usuario
}

SistemaDisponible -r-> AbrirUsuariosView: abrirUsuarios()
AbrirUsuariosView -d-> UsuarioController: listarUsuarios(filtros)
UsuarioController --> UsuarioRepository: findAll(filtros)
UsuarioRepository -- Usuario
@enduml