@startuml editarPregunta-analisis
skinparam linetype polyline

actor Docente
package editarPregunta as "editarPregunta()" {
    rectangle #629EF9 VistaEdicionPregunta
    rectangle #b5bd68 ControladorPreguntas
    rectangle #F2AC4E Pregunta
    rectangle #F2AC4E Asignatura
    rectangle #F2AC4E Tema
    rectangle #F2AC4E Respuesta
}

Docente -r-> VistaEdicionPregunta: modificarCampos(datos)
VistaEdicionPregunta -d-> ControladorPreguntas: guardarCambios(datos)
ControladorPreguntas --> Pregunta: actualizar(datos)
ControladorPreguntas --> Respuesta: actualizarRespuestas(respuestas)

Docente --> VistaEdicionPregunta: eliminarPregunta()
VistaEdicionPregunta --> ControladorPreguntas: eliminar()
ControladorPreguntas --> Pregunta: delete()

@enduml