@startsalt iniciarSesion-wireframe
{
    ====
    <b>GIPF - Gestor Investigadores y Proyectos de FUNIBER
    ====
    {^<b>Iniciar sesión
        Usuario    | "coordinador@funiber.org   "
        Contraseña | "********                 "
        {
            [Cancel] | [  OK   ]
        }
    }
}
@endsalt

@startsalt iniciarSesion-credenciales-incorrectas-wireframe
{
    ====
    <b>GIPF - Gestor Investigadores y Proyectos de FUNIBER
    ====
    {^<b>Iniciar sesión
        Usuario    | "coordinador@funiber.org   "
        Contraseña | "********                 "
        {
            [Cancel] | [  OK   ]
        }
    }
    **Credenciales incorrectas**
    ====
}
@endsalt

@startsalt iniciarSesion-credenciales-correctas-wireframe
{
    ====
    <b>GIPF - Gestor Investigadores y Proyectos de FUNIBER
    ====
    {^<b>Iniciar sesión
        Usuario    | "coordinador@funiber.org   "
        Contraseña | "********                 "
        {
            [Cancel] | [  OK   ]
        }
    }
    **Acceso correcto. Redirigiendo al Panel Principal...**
    ====
}
@endsalt
