@startuml crearProyecto-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":PROYECTOS_ABIERTOS" as EstadoEntrada
package crearProyecto as "crearProyecto()" {
    rectangle #629EF9 CrearProyectoView
    rectangle #b5bd68 ProyectoController
    rectangle #b5bd68 ProyectoService
    rectangle #b5bd68 SesionService
    rectangle #F2AC4E ProyectoRepository
    rectangle #F2AC4E ConvocatoriaRepository
    rectangle #F2AC4E Proyecto
    rectangle #F2AC4E Convocatoria
}

rectangle #CDEBA5 ":PROYECTO_ABIERTO" as EstadoSalida
rectangle #CDEBA5 ":PROYECTOS_ABIERTOS" as EstadoSalidaCancelada
rectangle #CDEBA5 ":Collaboration AbrirProyecto" as AbrirProyecto
rectangle #CDEBA5 ":Collaboration EditarProyecto" as EditarProyecto
rectangle #CDEBA5 ":Collaboration EliminarProyecto" as EliminarProyecto
rectangle #CDEBA5 ":Collaboration AgregarInvestigador" as AgregarInvestigador
rectangle #CDEBA5 ":Collaboration EliminarInvestigador" as EliminarInvestigador
rectangle #CDEBA5 ":Collaboration AbrirEntregables" as AbrirEntregables
rectangle #CDEBA5 ":Collaboration AbrirInvestigadores" as AbrirInvestigadores
rectangle #CDEBA5 ":Collaboration AbrirProyectos" as AbrirProyectos
rectangle #CDEBA5 ":Collaboration CrearProyecto" as CrearProyecto
rectangle #CDEBA5 ":Collaboration AbrirPanelPrincipal" as AbrirPanelPrincipal

EstadoEntrada -r-> CrearProyectoView: crearProyecto()

CrearProyectoView -d-> ProyectoController: prepararCreacion()
ProyectoController --> ProyectoService: crear(datos, coordinador)
ProyectoController --> SesionService: obtenerSesionActual(authentication)
ProyectoService --> ConvocatoriaRepository: obtenerDisponibles()
CrearProyectoView --> ProyectoController: crearProyecto(datosMinimos, coordinador)
ProyectoService --> ProyectoService: validarDatosYFechas(datosMinimos)
ProyectoService --> ProyectoService: asignarCodigoCoordinadorYEstadoCreado()
ProyectoService --> ProyectoRepository: guardar(proyecto)
ProyectoRepository -- Proyecto
ConvocatoriaRepository -- Convocatoria
CrearProyectoView ..> EstadoSalida: proyectoCreado()
CrearProyectoView ..> EstadoSalidaCancelada: cancelarCreacion()
CrearProyectoView ..> AbrirProyecto: abrirProyecto(proyectoId)
CrearProyectoView ..> EditarProyecto: editarProyecto()
CrearProyectoView ..> EliminarProyecto: eliminarProyecto()
CrearProyectoView ..> AgregarInvestigador: agregarInvestigador()
CrearProyectoView ..> EliminarInvestigador: eliminarInvestigador()
CrearProyectoView ..> AbrirEntregables: abrirEntregables()
CrearProyectoView ..> AbrirInvestigadores: abrirInvestigadores()
CrearProyectoView ..> AbrirProyectos: abrirProyectos()
CrearProyectoView ..> CrearProyecto: crearProyecto()
CrearProyectoView ..> AbrirPanelPrincipal: abrirPanelPrincipal()

@enduml
