@startuml abrirConvocatoria
skinparam linetype polyline

state in1 as "CONVOCATORIAS_ABIERTAS"
in1 -[#green]-> abrirConvocatoria

state abrirConvocatoria as "abrirConvocatoria()" {

    state " " as CargandoDetalle

    [*] -[#green]-> CargandoDetalle
    note on link
    <b>Coordinador</b> solicita abrir una convocatoria
    end note

    CargandoDetalle -[#green]-> [*]
    note on link
    <b>Sistema</b> presenta y visualiza la convocatoria solicitada
    <b>Sistema</b> muestra:
    • Título
    • Área
    • Estado
    • Fechas relevantes
    • Descripción
    • Requisitos y condiciones
    • Criterios de evaluación y dotación
    • Documentación asociada
    • Información de contacto

    <b>Sistema</b> permite solicitar:
    • Importar convocatoria
    • Volver a convocatorias
    end note
}

abrirConvocatoria -[#green]-> CONVOCATORIA_ABIERTA
note on link
Convocatoria mostrada
end note

abrirConvocatoria -[#green]-> CONVOCATORIAS_ABIERTAS
note on link
abrirConvocatorias()
end note

@enduml
