@startuml cancelarGeneracion-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":EXAMENES_GENERADOS" as ExamGen
rectangle #CDEBA5 ":EXAMENES_GENERADOS_CONTEXTUALES" as ExamGenCtx
rectangle #CDEBA5 ":SISTEMA_DISPONIBLE" as SistemaDisponible
rectangle #CDEBA5 ":ASIGNATURA_ABIERTO" as AsignaturaAbierto

package cancelarGeneracion as "cancelarGeneracion()" {
    rectangle #629EF9 CancelarGeneracionView
    rectangle #b5bd68 ExamenesController
}

ExamGen -r-> CancelarGeneracionView: cancelarGeneracion()
ExamGenCtx -r-> CancelarGeneracionView: cancelarGeneracion()

CancelarGeneracionView -> ExamenesController: cancelarGeneracion(examenes)

ExamenesController -> ExamenesController: borrarExamenesGenerados()

CancelarGeneracionView ..r.> SistemaDisponible
CancelarGeneracionView ..u.> AsignaturaAbierto

@enduml