@startuml consultarDetalleAlumno-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":Alumnos Abierto" as AlumnosAbierto

package consultarDetalleAlumno as "consultarDetalleAlumno()" {
    rectangle #629EF9 ConsultarDetalleAlumnoView
    rectangle #b5bd68 AlumnoController
    rectangle #F2AC4E AlumnoRepository
    rectangle #F2AC4E AsistenciaRepository
    rectangle #F2AC4E Alumno
    rectangle #F2AC4E Asistencia
}

AlumnosAbierto -r-> ConsultarDetalleAlumnoView: consultarDetalleAlumno()
ConsultarDetalleAlumnoView -d-> AlumnoController: consultarDetalleAlumno(alumnoId)
AlumnoController --> AlumnoRepository: findById(alumnoId)
AlumnoRepository -- Alumno
AlumnoController --> AsistenciaRepository: findByAlumno(alumnoId)
AsistenciaRepository -- Asistencia
@enduml