@startuml crearInvestigador
skinparam linetype polyline

state "INVESTIGADORES_ABIERTOS" as Investigadores
Investigadores -[#green]-> crearInvestigador: crearInvestigador()

state crearInvestigador as "crearInvestigador()" {
    state " " as SolicitandoDatos
    state " " as ValidandoDatos
    state " " as RegistrandoInvestigador

    [*] -[#green]-> SolicitandoDatos
    note on link
    <b>Coordinador</b> solicita crear investigador
    <b>Sistema</b> presenta solicitud de datos mínimos
    • Nombre de usuario, nombre completo y correo
    • Sede, unidad, línea de investigación y biografía
    • Permite solicitar registrar investigador
    • Permite solicitar cancelar creación
    end note

    SolicitandoDatos -[#green]-> ValidandoDatos
    note on link
    <b>Coordinador</b> proporciona datos mínimos
    end note

    ValidandoDatos -[#green]-> RegistrandoInvestigador
    note on link
    <b>Sistema</b> valida datos obligatorios y ausencia de duplicados
    end note

    RegistrandoInvestigador -[#green]-> [*]
    note on link
    <b>Sistema</b> registra el investigador activo
    end note
}

crearInvestigador -[#green]-> INVESTIGADOR_ABIERTO: Investigador creado
crearInvestigador -[#red]-> INVESTIGADORES_ABIERTOS: Creación cancelada o datos no válidos
@enduml
