@startuml editarMiembro-analisis
skinparam linetype polyline

actor Usuario
package editarMiembro as "editarMiembro()" {
    rectangle #629EF9 GestionarMiembrosView
    rectangle #b5bd68 MembresiasController
    rectangle #F2AC4E MiembroRepository
    rectangle #F2AC4E MiembroGrupo
}
rectangle #CDEBA5 ":Sistema Disponible" as SistemaDisponible

SistemaDisponible -r-> GestionarMiembrosView: 1: editarMiembro(grupo)

GestionarMiembrosView -d-> MembresiasController: 2: actualizarRol(idMiembro, nuevoRol)

MembresiasController --> MiembroRepository: 3: guardarCambios(idMiembro, nuevoRol)

MiembroRepository -- MiembroGrupo

GestionarMiembrosView -r-> SistemaDisponible: 4: sistemaDisponible(usuario)

@enduml
