@startuml iniciarSesion

skinparam linetype polyline

SESION_CERRADA -[#green]-> iniciarSesion

state iniciarSesion as "iniciarSesion()" {

    state " " as SolicitandoAcceso
    state " " as ProporcionandoCredenciales
    state c <<choice>>

    [*] -[#green]-> SolicitandoAcceso
    note on link
    <b>Investigador</b> solicita acceder al sistema
    end note

    SolicitandoAcceso -[#green]-> ProporcionandoCredenciales
    note on link
    <b>Sistema</b> permite introducir
    • usuario
    • contraseña
    end note

    ProporcionandoCredenciales -[#green]-> c
    note on link
    <b>Investigador</b> introduce
    • usuario
    • contraseña
    end note

    c -[#red]-> SolicitandoAcceso
    note on link
    <b>Sistema</b> presenta credenciales incorrectas
    end note

    c -[#green]-> [*]
    note on link
    <b>Sistema</b> presenta acceso correcto
    end note
}

iniciarSesion -[#green]-> PANEL_PRINCIPAL_ABIERTO
note on link
<b>Sistema</b> presenta panel principal
end note

@enduml
