@startuml crearProfesor-analisis
skinparam backgroundColor white
skinparam shadowing false
skinparam DefaultFontColor black
skinparam DefaultFontSize 12
skinparam linetype polyline

rectangle #CDEBA5 ":Profesores Abierto" as ProfesoresAbierto

package crearProfesor as "crearProfesor()" {
    rectangle #629EF9 CrearProfesorView
    rectangle #b5bd68 ProfesorController
    rectangle #F2AC4E ProfesorRepository
    rectangle #F2AC4E UsuarioRepository
    rectangle #F2AC4E Profesor
    rectangle #F2AC4E Usuario
}

rectangle #CDEBA5 ":Profesor Abierto" as ProfesorAbierto
rectangle #CDEBA5 ":Profesores Abierto" as ProfesoresAbiertoSalida

ProfesoresAbierto -r-> CrearProfesorView: crearProfesor()

CrearProfesorView -d-> ProfesorController: obtenerDepartamentosDisponibles() : List<String>

CrearProfesorView -d-> ProfesorController: crear(codigo, nombre, email, departamento) : Profesor

ProfesorController -d-> ProfesorRepository: existeEmail(email) : Boolean
ProfesorController -d-> UsuarioRepository: crearUsuario(email, password, rol) : Usuario
ProfesorController -r-> Profesor: <<create>>
ProfesorController -d-> ProfesorRepository: guardar(profesor)

Profesor -- Usuario

CrearProfesorView ..> ProfesorAbierto: <<finalizar>> editarProfesor(nuevoProfesor)
CrearProfesorView ..> ProfesoresAbiertoSalida: <<cancelar>>

@enduml
