@startuml abrirEntregable
skinparam linetype polyline

state in1 as "ENTREGABLES_ABIERTOS"
in1 -[#green]-> abrirEntregable

state abrirEntregable as "abrirEntregable()" {

    state " " as SolicitandoApertura
    state " " as MostrandoListado
    state " " as SeleccionandoEntregable

    [*] -[#green]-> SolicitandoApertura
    note on link
    <b>Coordinador</b> solicita abrir un entregable
    end note

    SolicitandoApertura -[#green]-> MostrandoListado
    note on link
    <b>Sistema</b> presenta y visualiza el listado de entregables
    <b>Sistema</b> muestra información:
    • ID
    • Título
    • Tipo
    • Fecha límite
    • Estado
    • Descripción (si aplica)
    • Archivo adjunto (si aplica)

    <b>Sistema</b> permite solicitar:
    • Editar entregable
    • Eliminar entregable
    • Volver a entregables
        end note

    MostrandoListado -[#green]-> SeleccionandoEntregable
    note on link
    <b>Coordinador</b> solicita abrir un entregable del listado
    end note

    SeleccionandoEntregable -[#green]-> [*]
    note on link
    <b>Sistema</b> presenta y visualiza el entregable solicitado
    end note
}

abrirEntregable -[#green]-> ENTREGABLE_ABIERTO
note on link
Entregable abierto
end note

abrirEntregable -[#green]-> ENTREGABLE_ABIERTO
note on link
editarEntregable()
end note

abrirEntregable -[#green]-> ENTREGABLES_ABIERTOS
note on link
eliminarEntregable()
end note

abrirEntregable -[#green]-> ENTREGABLES_ABIERTOS
note on link
abrirEntregables()
end note

@enduml
