@startuml editarPregunta-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":Preguntas Abierto" as PreguntasAbierto
rectangle #CDEBA5 ":Preguntas Contextuales Abierto" as PreguntasContextualesAbierto
rectangle #CDEBA5 ":Pregunta Abierto" as PreguntaAbierto
rectangle #CDEBA5 ":Pregunta Contextual Abierto" as PreguntaContextualAbierto
rectangle #CDEBA5 ":Respuestas Abierto" as RespuestasAbierto
rectangle #CDEBA5 ":Respuestas Contextual Abierto" as RespuestasContextualAbierto
rectangle #CDEBA5 ":Collaboration crearPregunta" as CrearPregunta
rectangle #CDEBA5 ":Collaboration verRespuestas" as VerRespuestas
rectangle #CDEBA5 ":Collaboration eliminarPregunta" as EliminarPregunta
rectangle #CDEBA5 ":Collaboration verPreguntas" as VerPreguntas

package editarPregunta as "editarPregunta()" {
    rectangle #629EF9 EditarPreguntaView
    rectangle #b5bd68 PreguntasController
    rectangle #F2AC4E PreguntaRepository
    rectangle #F2AC4E Pregunta
    rectangle #F2AC4E Respuesta
}

CrearPregunta --> EditarPreguntaView: editarPregunta(preguntaNueva)
PreguntasAbierto --> EditarPreguntaView: editarPregunta(preguntaId)
PreguntasContextualesAbierto --> EditarPreguntaView: editarPregunta(preguntaId)
PreguntaAbierto --> EditarPreguntaView: editarPregunta(preguntaId)
PreguntaContextualAbierto --> EditarPreguntaView: editarPregunta(preguntaId)
RespuestasAbierto --> EditarPreguntaView: editarPregunta(preguntaId)
RespuestasContextualAbierto --> EditarPreguntaView: editarPregunta(preguntaId)

EditarPreguntaView -d-> PreguntasController: cargarPreguntaParaEdición(preguntaId) : Pregunta

PreguntasController --> PreguntaRepository: obtenerPorId(preguntaId) : Pregunta

PreguntaRepository -- Pregunta
Pregunta -- Respuesta

EditarPreguntaView --> PreguntasController: modificarCampos(preguntaId, cambios) : boolean

PreguntasController --> PreguntaRepository: actualizar(pregunta) : boolean

EditarPreguntaView ..> VerRespuestas: <<include>> verRespuestas(preguntaId)
EditarPreguntaView ..> EliminarPregunta: <<include>> eliminarPregunta(preguntaId)
EditarPreguntaView ..> VerPreguntas: <<include>> verPreguntas()

@enduml