@startuml abrirSolicitudEliminacionPerfil-diseño
skinparam style strictuml
skinparam backgroundColor white
skinparam shadowing false

actor Coordinador
participant "Cloudflare\n(React)" as View
participant "Render\n(NestJS)" as Controller
participant "SolicitudEliminacionRepository\n(TypeORM)" as Repo

Coordinador -> View: abrirSolicitudEliminacionPerfil(solicitudId)
activate View

View -> Controller: abrirSolicitudEliminacionPerfil(solicitudId)
activate Controller

Controller -> Repo: abrirSolicitudEliminacionPerfil(solicitudId)
activate Repo

Repo --> Controller: solicitud
deactivate Repo

Controller --> View: solicitud
deactivate Controller

View --> Coordinador: mostrarDetalle(solicitud)
deactivate View
@enduml
