@startuml abrirRecompensas

skinparam linetype polyline

state in1 as "RECOMPENSA_ABIERTA"
in1 -[#green]-> abrirRecompensas
note on link
abrirRecompensas()
end note

state in2 as "PANEL_PRINCIPAL_ABIERTO"
in2 -[#green]-> abrirRecompensas
note on link
abrirRecompensas()
end note

state abrirRecompensas as "abrirRecompensas()" {

    state " " as MostrandoListado
    state " " as FiltrandoListado

    [*] -[#green]-> MostrandoListado
    note on link
    <b>Investigador</b> solicita abrir recompensas
    end note

    MostrandoListado -[#green]-> FiltrandoListado
    note on link
    <b>Sistema</b> presenta listado de recompensas
    • Tipo
    • Cantidad
    <b>Sistema</b> permite solicitar:
    • abrir recompensa
    
    end note

    FiltrandoListado -[#green]-> [*]
    note on link
    <b>Investigador</b> solicita una opción del listado
    end note
}


abrirRecompensas -[#green]-> RECOMPENSAS_ABIERTAS
note on link
Recompensas abiertas
end note

abrirRecompensas -[#green]-> RECOMPENSA_ABIERTA
note on link
abrirRecompensa()
end note

abrirRecompensas -[#green]-> PANEL_PRINCIPAL_ABIERTO
note on link
abrirPanelPrincipal()
end note


@enduml
