@startuml crearRespuesta-analisis
skinparam linetype polyline

actor Docente
package crearRespuesta as "crearRespuesta()" {
    rectangle #629EF9 VistaCreacionRespuesta
    rectangle #b5bd68 ControladorCreacionRespuestas
    rectangle #F2AC4E Respuesta
    rectangle #F2AC4E Pregunta
}

Docente -r-> VistaCreacionRespuesta: solicitarCrear()
VistaCreacionRespuesta --> Docente: pedirDatos()
Docente --> VistaCreacionRespuesta: proporcionarDatos()
VistaCreacionRespuesta -d-> ControladorCreacionRespuestas: crearRespuesta()
ControladorCreacionRespuestas --> Respuesta: new()
ControladorCreacionRespuestas --> Pregunta: addAnswer()

@enduml