@startuml
Title Casos de Uso: Alumno
left to right direction
skinparam style strictuml

actor Alumno

package "Módulo Dispensas (Vista Alumno)" {
    usecase "Abrir dispensas" as AbrirDispensas
    usecase "Crear solicitud de dispensa" as CrearSolicitudDispensa
    usecase "Consultar estado de dispensa" as ConsultarEstadoDispensa
    usecase "Editar solicitud de dispensa" as EditarSolicitudDispensa
}

Alumno --> AbrirDispensas
Alumno --> CrearSolicitudDispensa
Alumno --> ConsultarEstadoDispensa
Alumno --> EditarSolicitudDispensa
@enduml