@startuml
Title Casos de Uso: Secretaría Académica
left to right direction
skinparam style strictuml

actor SecretariaAcademica

package "Módulo Alumnos" {
    usecase "Abrir alumnos" as AlumnosAbrir
    usecase "Importar alumnos" as AlumnosImportar
    usecase "Consultar alumno" as AlumnosConsultar
}

package "Módulo Matrículas" {
    usecase "Abrir matrículas" as MatriculasAbrir
    usecase "Importar matrículas" as MatriculasImportar
    usecase "Consultar detalle de matrícula" as MatriculasVerDetalle
    usecase "Cerrar ciclo académico" as MatriculasCerrarCiclo
}

package "Módulo Dispensas" {
    usecase "Abrir dispensas" as DispensasAbrir
    usecase "Crear solicitud de dispensa" as DispensasCrear
    usecase "Consultar solicitud de dispensa" as DispensasConsultar
    usecase "Editar solicitud de dispensa" as DispensasEditar
}

SecretariaAcademica --> AlumnosAbrir
SecretariaAcademica --> AlumnosImportar
SecretariaAcademica --> AlumnosConsultar

SecretariaAcademica --> MatriculasAbrir
SecretariaAcademica --> MatriculasImportar
SecretariaAcademica --> MatriculasVerDetalle
SecretariaAcademica --> MatriculasCerrarCiclo

SecretariaAcademica --> DispensasAbrir
SecretariaAcademica --> DispensasCrear
SecretariaAcademica --> DispensasConsultar
SecretariaAcademica --> DispensasEditar
@enduml