@startuml abrirInvestigador-analisis
skinparam linetype polyline

actor "Investigador" as ActorInvestigador
rectangle #CDEBA5 ":INVESTIGADORES_ABIERTOS" as InvestigadoresAbiertos
package abrirInvestigador as "abrirInvestigador(idInvestigador)" {
    rectangle #629EF9 DetalleInvestigadorView
    rectangle #b5bd68 InvestigadorController
    rectangle #b5bd68 InvestigadorService
    rectangle #b5bd68 SesionService
    rectangle #F2AC4E InvestigadorRepository
    rectangle #F2AC4E ProyectoRepository
    rectangle #F2AC4E Investigador
    rectangle #F2AC4E Proyecto
}
rectangle #CDEBA5 ":INVESTIGADOR_ABIERTO" as InvestigadorAbierto
rectangle #CDEBA5 ":Collaboration AbrirInvestigadores" as AbrirInvestigadores
rectangle #CDEBA5 ":Collaboration AbrirProyectos" as AbrirProyectos

ActorInvestigador -- InvestigadoresAbiertos
InvestigadoresAbiertos -r-> DetalleInvestigadorView: abrirInvestigador(idInvestigador)
DetalleInvestigadorView -d-> InvestigadorController: obtenerInvestigadorActivo(idInvestigador) : Investigador
InvestigadorController --> InvestigadorService: obtener(sesion, id, proyectoId?)
InvestigadorController --> SesionService: obtenerSesionActual(authentication)
InvestigadorService --> InvestigadorRepository: obtenerActivoPorId(idInvestigador) : Investigador
DetalleInvestigadorView --> InvestigadorController: listarProyectosVisibles(idInvestigador, ActorInvestigador) : List<Proyecto>
InvestigadorService --> ProyectoRepository: obtenerVisiblesCompartidos(idInvestigador, ActorInvestigador) : List<Proyecto>
InvestigadorRepository -- Investigador
ProyectoRepository -- Proyecto
DetalleInvestigadorView ..> InvestigadorAbierto: investigadorPresentado()
DetalleInvestigadorView ..> AbrirInvestigadores: abrirInvestigadores()
DetalleInvestigadorView ..> AbrirProyectos: abrirProyectos()
@enduml
