@startuml corregirExamenes-analisis
skinparam linetype polyline

actor Docente
package corregirExamenes as "corregirExamenes()" {
    rectangle #629EF9 VistaCorreccion
    rectangle #b5bd68 ControladorCorreccion
    rectangle #F2AC4E Examen
    rectangle #F2AC4E Alumno
}

Docente -r-> VistaCorreccion: iniciarCorreccion()
VistaCorreccion -d-> ControladorCorreccion: corregirExamenes(archivos)
ControladorCorreccion --> Examen: validarClave()
ControladorCorreccion --> Alumno: asociarAlumno()
ControladorCorreccion --> Examen: actualizarEstado(Corregido)

@enduml