@startuml abrirInvestigador

skinparam linetype polyline

state in1 as "OPCIONES_PERFIL_ABIERTO"
in1 -[#green]-> abrirInvestigador
note on link
abrirInvestigador(ID)
end note

state in2 as "INVESTIGADORES_ABIERTOS"
in2 -[#green]-> abrirInvestigador
note on link
abrirInvestigador()
end note


state abrirInvestigador as "abrirInvestigador()" {

    state " " as MostrandoLista
    state " " as FiltrandoLista

    [*] -[#green]-> MostrandoLista 
    note on link
    <b>Coordinador</b> solicita abrir investigador
    end note    
    
    MostrandoLista -[#green]-> FiltrandoLista
    note on link
    <b>Sistema</b> presenta perfil de investigador
    • ID, nombre, apellido, campo, carrera, master y rol de cada investigador
    • Permite solicitar editar perfil
    • Permite solicitar abrirInvestigadores

  
    

    end note
    FiltrandoLista -[#green]-> [*]
    note on link
    <b>Coordinador</b> solicita una de las opciones
    end note
}

abrirInvestigador -[#green]-> INVESTIGADOR_ABIERTO
note on link
Investigador mostrado
end note

abrirInvestigador -[#green]-> OPCIONES_PERFIL_ABIERTO
note on link
abrirOpcionesPerfil()
end note

abrirInvestigador -[#green]-> INVESTIGADORES_ABIERTOS
note on link
abrirInvestigadores()
end note

abrirInvestigador -[#green]-> PROYECTOS_ABIERTOS
note on link
abrirProyectos()
end note



@enduml