@startuml abrirInvestigador-diseño
skinparam style strictuml
skinparam backgroundColor white
skinparam shadowing false
skinparam DefaultFontColor black
skinparam DefaultFontSize 12
skinparam linetype polyline

actor Usuario
participant "Cloudflare\n(React)" as View
participant "Render\n(NestJS)" as Controller
participant "InvestigadorRepository\n(TypeORM)" as Repository

Usuario -> View: abrirInvestigador(investigadorId)
activate View

View -> Controller: abrirInvestigador(investigadorId)
activate Controller

Controller -> Repository: abrirInvestigador(investigadorId)
activate Repository

Repository --> Controller: Investigador
deactivate Repository

Controller --> View: Investigador
deactivate Controller

View --> Usuario: mostrarPerfil(Investigador)
deactivate View

@enduml