@startuml definirLocalizacion
skinparam monochrome false
skinparam shadow false
top to bottom direction

skinparam state {
    BackgroundColor White
    BorderColor Black
    ArrowColor #009900
    StartColor Black
    EndColor Black
}

skinparam note {
    BackgroundColor #FFFFE0
    BorderColor #B0B060
    FontName Arial
}

state "PLANIFICACION_ABIERTO" as Inicio

state "definirLocalizacion()" as DefinirLocalizacionContainer {
    top to bottom direction

    state " " as PasoInicial
    state " " as PasoDatos

    [*] --> PasoInicial
    note on link
        **Usuario** solicita definir localización
    end note

    PasoInicial --> PasoDatos
    note on link
        **Sistema** presenta mapa y buscador
        **Sistema** permite solicitar:
        • introducir coordenadas o dirección
        • guardar localización
        • cancelar localización
    end note

    PasoDatos -[#green]-> [*]
    note on link
        **Usuario** introduce los datos y solicita guardar
    end note

    PasoDatos -[#red]-> [*]
    note on link
        **Usuario** solicita cancelar localización
    end note
}

state "PLANIFICACION_ABIERTO" as SalidaPlanificacion

Inicio --> DefinirLocalizacionContainer

DefinirLocalizacionContainer -[#green]-> SalidaPlanificacion
note on link
    guardar localización
end note

DefinirLocalizacionContainer -[#red]-> SalidaPlanificacion
note on link
    cancelar localización
end note

@enduml