@startuml completarGestion-analisis
skinparam linetype polyline
left to right direction

actor Usuario
boundary TareasView
control DashboardController
rectangle ":Sistema Disponible" as SistemaDisponible #C5E0B4

Usuario --> TareasView : 1: completarGestion()
TareasView --> DashboardController : 2: verificarYVolver()
DashboardController --> SistemaDisponible : 3: actualizaEstado()

@enduml
