@startuml resolverSolicitudEliminacionPerfil

skinparam linetype polyline

state in1 as "SOLICITUD_ELIMINACION_PERFIL_ABIERTA"
in1 -[#green]-> resolverSolicitudEliminacionPerfil
note on link
resolverSolicitudEliminacionPerfil()
end note

state resolverSolicitudEliminacionPerfil as "resolverSolicitudEliminacionPerfil()" {

    state " " as ListandoSolicitudes
    state " " as EvaluandoSolicitud
    state " " as Resultado

    [*] -[#green]-> ListandoSolicitudes
    note on link
    <b>Coordinador</b> solicita abrir solicitudes pendientes
    end note

    ListandoSolicitudes -[#green]-> EvaluandoSolicitud
    note on link
    <b>Sistema</b> muestra lista de solicitudes de eliminación de perfil
    • ID, nombre, campo
    end note

    EvaluandoSolicitud -[#green]-> Resultado
    note on link
    <b>Coordinador</b> solicita aprobar o rechazar solicitud
    <b>Sistema</b> presenta estado del perfil
    end note

    EvaluandoSolicitud -[#red]-> ListandoSolicitudes
    note on link
    <b>Coordinador</b> cancela la operación
    end note

    Resultado -[#green]-> [*]
    
}


resolverSolicitudEliminacionPerfil -[#green]-> OPCIONES_PERFIL_ABIERTO
note on link
abrirOpcionesPerfil()
end note



@enduml
