@startuml editarPerfil-analisis
skinparam backgroundColor white
skinparam shadowing false
skinparam DefaultFontColor black
skinparam DefaultFontSize 12
skinparam linetype polyline

rectangle #CDEBA5 "OPCIONES_PERFIL_ABIERTO" as OpcionesPerfilAbierto

package "editarPerfil()" as editarPerfil {
    rectangle "EditarPerfilView" as EditarPerfilView #629EF9
    rectangle "EditarPerfilController" as EditarPerfilController #b5bd68
    rectangle "UsuarioRepository" as UsuarioRepository #F2AC4E
    rectangle "Sesion" as Sesion #F2AC4E
}

OpcionesPerfilAbierto -r-> EditarPerfilView: editarPerfil()

EditarPerfilView -d-> EditarPerfilController: cargarDatosActuales()
EditarPerfilController -d-> Sesion: getUsuarioActual() : Usuario
EditarPerfilController -d-> UsuarioRepository: obtenerPorId(usuarioId) : Usuario

EditarPerfilView -d-> EditarPerfilController: guardarCambios(datosNuevos) : boolean
EditarPerfilController -d-> UsuarioRepository: actualizar(usuario) : boolean

EditarPerfilView ..> OpcionesPerfilAbierto: <<finalizar>> confirmar()
EditarPerfilView ..> OpcionesPerfilAbierto: <<cancelar>> cancelar()

@enduml
